### ISSUE TITLE
Derived data warning on 3.3.1

### ISSUE THREAD

**Issue by adipurnama** [AppsFlyerSDK/AppsFlyerFramework#1]
Hi AppFlyer team,

I was just updating my app with Appflyer 3.3.1. Everything went fine & clean with version 3.3.0, but after update to 3.3.1 using cocoapods i got these following warnings :

*no such file/derived data warning* :
`warning: /Users/golan/Library/Developer/Xcode/DerivedData/AppsFlyerLib-ahecwkkcwzvaoqdfeixypezvtbys/Build/Intermediates/PrecompiledHeaders/AppsFlyerLib-Prefix-hjiknwycdpkteehfgiqxklkyhuiw/AppsFlyerLib-Prefix.pch.pch: No such file or directory`

*and about several "could not resolve external type" warnings* :
`warning: Could not resolve external type c:objc(cs)NSObject`
`warning: Could not resolve external type c:objc(cs)NSMutableArray`
`warning: Could not resolve external type c:objc(cs)NSNumber`
-- about 30 warning like this --

I've tried to clean & rebuild the project on xcode 7, also re-install from cocoapods but the warning keeps showing. FYI, our app support for minimum OS 7.
Could you guys help me regarding this issue ? Is there any additional XCode settings/configurations that I am not aware of to solve this ?

Thank you.

**Comment by alvaromurillo** [comment]
I have the same problem, supporting iOS7, Xcode 7 and Bitcode Enabled.

**Comment by golan19** [comment]
Fixed

**Comment by alvaromurillo** [comment]
@golan19 now is broken for the simulator.
```
ld: warning: ignoring file /workspace/xxxx/Pods/AppsFlyer-SDK/libAppsFlyerLib.a, missing required architecture x86_64 in file /workspace/xxxx/Pods/AppsFlyer-SDK/libAppsFlyerLib.a (2 slices)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AppsFlyerTracker", referenced from:
      objc-class-ref in AppDelegate.o
      objc-class-ref in MixpanelHelper.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by golan19** [comment]
@alvaromurillo: How do you integrate the SDK? as a framework? or a static lib?

**Comment by alvaromurillo** [comment]
A static lib.

**Comment by golan19** [comment]
@alvaromurillo: Where did you get the static lib? this is the framework repository

**Comment by alvaromurillo** [comment]
@golan19  Ok, what I mean is that I'm integrating the library with cocoapods as static library.

**Comment by alvaromurillo** [comment]
@golan19 I get the same error with the pods:
pod 'AppsFlyer-SDK', '~> 3.3'
pod 'AppsFlyerFramework', '~> 3.3'

**Comment by golan19** [comment]
@alvaromurillo: Please check your code, make sure the SDK is updated to the new version, I checked both pods and both are working with the simulator.

**Comment by adipurnama** [comment]
@golan19 
Thanks for the fix. Everything's clean now.

@alvaromurillo 
Try to use only `pod AppsFlyer-SDK` on your Podfile. It works for me.

**Comment by alvaromurillo** [comment]
@golan19 I create this [sample project](https://github.com/alvaromurillo/AppsFlyerSample) and get the same error.

**Comment by golan19** [comment]
@alvaromurillo: You have the old SDK, If you create a new project you will get the updated SDK.
Or you just can remove the pod AppsFlyer-SDK from the pod file, run pod update then re-enter the pod AppsFlyer-SDK back to the pod file and run pod update again.

**Comment by alvaromurillo** [comment]
@golan19 The project is new, I just created it for you, as you can see in the [Podfile.lock](https://github.com/alvaromurillo/AppsFlyerSample/blob/master/Podfile.lock) it's using the last version AppsFlyer-SDK (3.3.2).

**Comment by alvaromurillo** [comment]
@golan19 Ok, I fix it cleaning the cocoapods cache. Thanks a lot!

**Comment by manishsharma93** [comment]
I am also facing the same issue. Please help

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AppsFlyerTracker", referenced from:
      objc-class-ref in DemoViewController.o
      objc-class-ref in GreenViewController.o

Thanks in advance.
