### ISSUE TITLE
AppsFlyer-SDK 4.3.6 crash on iOS 7

### ISSUE THREAD

**Issue by Agarunov** [AppsFlyerSDK/AppsFlyerFramework#10]
Crash on iOS 7 when call [AppsFlyerTracker sharedTracker]

+[NSURLSessionConfiguration backgroundSessionConfigurationWithIdentifier:]: unrecognized selector sent to class 0x39f2c05c

Method backgroundSessionConfigurationWithIdentifier: of NSURLSessionConfiguration class only available from iOS 8 and above

**Comment by golan19** [comment]
Fixed
