### ISSUE TITLE
AppsFlyerTracker/AppsFlyerTracker.h failed

### ISSUE THREAD

**Issue by HyEnjoys** [AppsFlyerSDK/AppsFlyerFramework#100]
#import <AppsFlyerTracker/AppsFlyerTracker.h> should be changed to
#import <AppsFlyerLib/AppsFlyerTracker.h>

**Comment by af-fess** [comment]
hi @HyEnjoys please provide basic information about your environment, such:
- AppsFlyer SDK version
- framework: dynamic|static|cocoapods

**Comment by andr-ggn** [comment]
thx, changed in doc
