### ISSUE TITLE
Mac Catalyst support discussion

### ISSUE THREAD

**Issue by chethanashastry** [AppsFlyerSDK/AppsFlyerFramework#101]
We are using the appsflyer SDK in our project. Since we are planning to support for mac, is there a SDK available with catalyst support for mac? Is it in the pipeline?

**Comment by andr-ggn** [comment]
Next AppsFlyerFramework should support Catalyst.
Next week.

**Comment by andr-ggn** [comment]
https://github.com/AppsFlyerSDK/AppsFlyerFramework/releases/tag/5.1.0-beta.1

This is beta, so there might be some issues

**Comment by chethanashastry** [comment]
Thanks a lot for the timely support. The compilation issue is resolved.

**Comment by andr-ggn** [comment]
Please, post any Catalyst project issues here. thx

**Comment by itayAmza** [comment]
@andr-ggn Do you guys have any timeline for when the Mac Catalyst xcframework will be available via Cocoapods?

**Comment by andr-ggn** [comment]
We will wait until Cocoapods will be released with xcframework support(not a beta) and only then will push there

**Comment by andr-ggn** [comment]
For now you can download it directly and include it in old fashion way

**Comment by xiao99xiao** [comment]
Cocoapods with XCFramework is already here. Firebase SDK is releasing new versions in XCFrameworks.

**Comment by henrytkirk** [comment]
I'm receiving an error compiling for Catalyst:

`.../AppsFlyerLib.framework/AppsFlyerLib(AFSDKKeychainFactory.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, file '.../AppsFlyerLib.framework/AppsFlyerLib' for architecture x86_64
`
I'm using the latest version via cocoapods.

**Comment by andr-ggn** [comment]
@henrytkirk To support Mac Catalyst add framework manually from this repo. Our cocoapods does not support Catalyst yet.

**Comment by xiao99xiao** [comment]
@andr-ggn Is there any blocker issues that keep you from pushing the XCFrameworks version to Cocoapods?

**Comment by andr-ggn** [comment]
Good news! 5.4.0 will contain Mac Catalyst support! ~2 weeks

**Comment by anatoliykant** [comment]
Guys, what about version 5.4.0, when can I wait?

**Comment by danwey** [comment]
~2 weeks after........5.4.0 where is?

**Comment by andr-ggn** [comment]
- 5.4.0 (2020-06-03 06:27:55 UTC)

**Comment by af-fess** [comment]
https://github.com/AppsFlyerSDK/AppsFlyerFramework/blob/master/AppsFlyerFramework.podspec

**Comment by gang018** [comment]
> @andr-ggn I'm running 5.4.4 via cocoapods 1.9.3 on Xcode 11.6 and am seeing the issue @henrytkirk was having before this was 'fixed'. I also tried version 5.4.0 of the pod to make sure it haven't rebroken... but still getting:
> 
> In /Users/default/Development/weve/weve-app-ios/Pods/AppsFlyerFramework/iOS/AppsFlyerLib.framework/AppsFlyerLib(AppsFlyerHTTPClient.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, file '/Users/default/Development/weve/weve-app-ios/Pods/AppsFlyerFramework/iOS/AppsFlyerLib.framework/AppsFlyerLib' for architecture x86_64

Hi. I have the same problem using 6.0.3

**Comment by victorBaro** [comment]
Same problem here using latest version

**Comment by xiao99xiao** [comment]
@andr-ggn I can confirm the issue regressed in 6.0.x version.

**Comment by thefaj** [comment]
Thirded—it's broken in 6.0.3. Any fix from the company on this showstopper?

**Comment by victorBaro** [comment]
I opened https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/134 which might be related?

**Comment by thefaj** [comment]
> I opened #134 which might be related?

Thanks—I added a comment there. Kind of disappointing there isn't a response yet.

**Comment by Nekitosss** [comment]
Please fix support for Mac catalyst
