### ISSUE TITLE
not parsed onAppOpenAttribution af_dp field when long link clicked

### ISSUE THREAD

**Issue by dhhyuk** [AppsFlyerSDK/AppsFlyerFramework#104]
# Report

## SDK Version

4.9.0

## What did you do?

parse onAppOpenAttribution attributionData parameters when
clicked long link.

## What did you expect to happen?

get each parameter on attributionData

## What happened instead?

not parsed parameters, only get 'link' field with value "long link"

long link has 'af_dp'.. 'pid'.. but fields only 'link'

## Please provide any other relevant information.

<img width="312" alt="스크린샷 2019-12-19 오후 6 56 02" src="https://user-images.githubusercontent.com/15702172/71164023-998d5480-2291-11ea-88b5-b50f0a9732b8.png">

**Comment by andr-ggn** [comment]
Hi, add add `&af_deeplink=true` param to your URL.
Example: `https://domain.onelink.me/SOME_KEY?param1=value1&param2=value2&&af_deeplink=true

**Comment by dhhyuk** [comment]
> Hi, add `&af_deeplink=true` param to your URL.
> Example: https://domain.onelink.me/SOME_KEY?param1=value1&param2=value2&af_deeplink=true

af_dp with af_deeplink??

**Comment by andr-ggn** [comment]
try add as additional param: `af_dp=your_param&af_deeplink=true`

**Comment by dhhyuk** [comment]
it's work!
so, why not added param in generate onelink in appsflyer web?

**Comment by andr-ggn** [comment]
Historically, the SDK only resolves ShortLinks and LongLinks with `af_deeplink`.
Need to figure it out.
I will add a feature request.
