### ISSUE TITLE
Installing framework trough Carthage doesn't install latest version.

### ISSUE THREAD

**Issue by TimPapler** [AppsFlyerSDK/AppsFlyerFramework#107]
# Report

## SDK Version

`5.0.0`

## What did you do?

Run `carthage update`
In cartfile there is:
```binary "https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/AppsFlyerTracker.json"```

## What did you expect to happen?

Expected to have AppsFlyer framework version ```5.1.0```

## What happened instead?

Got ```5.0.0``` version instead
## Please provide any other relevant information.

https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/AppsFlyerTracker.json is missing latest version. It seems carthage support is lagging behind since this is not the first time this has happened. The 5.1.0 version was released more than a month ago.

**Comment by andr-ggn** [comment]
– Install the latest version of Carthage
– Add the following line to your Cartfile binary:
`https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/AppsFlyerLib.json`
**Note:**
– The url above links to a **static framework**. If you're upgrading to a newer iOS version, do the following:
Remove the Run Script stage from Xcode that runs copy-frameworks.
Make sure the library is not embedded.

**Comment by TimPapler** [comment]
This is great news! Thank you! 👍
