### ISSUE TITLE
SceneDelegate support

### ISSUE THREAD

**Issue by ildarsharafutdinov** [AppsFlyerSDK/AppsFlyerFramework#109]
hi,

Appsflyer doesn't recognize deeplinks on iOS 13. I checked a clean project and found out, that a number of AppDelegate methods are not called. Particularly the following one:

```
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
```

However, SceneDelegate method is called instead:
```
- (void)scene:(UIScene *)scene continueUserActivity:(NSUserActivity *)userActivity
```

So does AppsFlyer support SceneDelegate?
Is there an instruction on how to use AppsFlyer & SceneDelegate?

**Comment by andr-ggn** [comment]
https://support.appsflyer.com/hc/en-us/articles/207032066-iOS-SDK-integration-for-developers#integration

`CMD+F SceneDelegate`
