### ISSUE TITLE
HandleOpenURL issues

### ISSUE THREAD

**Issue by bdrelling** [AppsFlyerSDK/AppsFlyerFramework#11]
We're having issues with the following call:

`AppsFlyerTracker.sharedTracker().handleOpenURL(url, sourceApplication: sourceApplication, withAnnotaion: annotation)`

It is crashing the app very infrequently and we're not sure why. We've had AppsFlyer integrated into our app for some time now. Can't seem to figure out what is causing it.

In addition to this:

- It should be optimized to return a boolean to allow for halting the OpenURL call at that point. Any reason it doesn't?
- "withAnnotation" is spelled wrong.

**Comment by gmeroz** [comment]
Do you have a log of the crash?
