### ISSUE TITLE
Carthage versions

### ISSUE THREAD

**Issue by cschelly** [AppsFlyerSDK/AppsFlyerFramework#110]
The latest version in the AppsFlyerTracker.json file is `5.0.0`, can `5.1.0` and `5.2.0` be added so we can pull in the latest version with Carthage? Thanks!

**Comment by andr-ggn** [comment]
Hi, please switch to 
`https://github.com/AppsFlyerSDK/AppsFlyerFramework/blob/master/AppsFlyerLib.json`
