### ISSUE TITLE
AppsFlyerLib.json Invalid URL for Version 5.2.0

### ISSUE THREAD

**Issue by kravtsovguy** [AppsFlyerSDK/AppsFlyerFramework#111]
invalid url for 5.2.0 version
https://github.com/AppsFlyerSDK/AppsFlyerFramework/releases/download/5.2.0/AppsFlyerLib.framework.zip

**Comment by andr-ggn** [comment]
Check now
Thanks!

**Comment by kravtsovguy** [comment]
Fixed, nice!
