### ISSUE TITLE
Carthage update go  in error 500

### ISSUE THREAD

**Issue by pjcau** [AppsFlyerSDK/AppsFlyerFramework#112]
Hi Guys, 
I need this library as dependency and go in error 500/503 with carthage and block the carthage update. Can you fix it, please?

https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/AppsFlyerTracker.json 

# Report

## What did you do?
carthage update

**Comment by andr-ggn** [comment]
`https://www.githubstatus.com`
