### ISSUE TITLE
AppsFlyerLib.json not updated for Carthage

### ISSUE THREAD

**Issue by NiltiakSivad** [AppsFlyerSDK/AppsFlyerFramework#119]
## SDK Version

5.2.0

## What did you do?

Ran carthage update --platform iOS

## What did you expect to happen?

To get the latest AppsFlyer build available which is 5.4.1

## What happened instead?

It thinks 5.2.0 is the latest version because

these links were updated https://github.com/AppsFlyerSDK/AppsFlyerFramework/commit/b5e679879e6bc63753353c8df20cd8aa081151a8

but https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/AppsFlyerLib.json have not been updated to include links to the latest binary version numbers.

**Comment by andr-ggn** [comment]
`binary "https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/Carthage/appsflyer-ios.json"`

**Comment by NiltiakSivad** [comment]
@andr-ggn The README.md on the project repo should be updated as that link does not reflect the current documentation reference of: 

![image](https://user-images.githubusercontent.com/4063424/91082892-960f5180-e606-11ea-8af4-6c441f2e2c0b.png)

The file should be deleted too to limit confusion.
