### ISSUE TITLE
Can't Compile on Xcode 12 Beta 4

### ISSUE THREAD

**Issue by dacoinminster** [AppsFlyerSDK/AppsFlyerFramework#121]
# Report

## SDK Version

5.4.1
(latest available via pod install)

(Also tried latest beta version of AppsFlyer)

## What did you do?

Upgraded from Xcode 12 Beta 3 to Xcode 12 Beta 4

## What did you expect to happen?

Expected that my project would continue to compile with the AppsFlyer SDK installed

## What happened instead?

When I try to compile, I get a linker error:

ld: in /Users/j.r.willett/Documents/GitHub/cozi/ios/app/iCozi/Pods/AppsFlyerFramework/iOS/AppsFlyerLib.framework/AppsFlyerLib(AFSDKChecksum.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/j.r.willett/Documents/GitHub/cozi/ios/app/iCozi/Pods/AppsFlyerFramework/iOS/AppsFlyerLib.framework/AppsFlyerLib' for architecture arm64

## Please provide any other relevant information.

Online resources about this error seem to indicate that only AppsFlyer can fix this problem:

> If this library is from a framework vendor (either as source or a pre-compiled binary), or you integrate a vendor's library into your app with a third party dependency manager, please consult with the library vendor or dependency manager for support.

(Found here: https://developer.apple.com/forums/thread/130684)

Does this mean AppsFlyer cannot be used with newest XCode until you release a new version of your framework??

**Comment by andr-ggn** [comment]
MacCatalyst is on?

**Comment by dacoinminster** [comment]
No we specified to only build for ios (iphone and ipad). Mac is unchecked. Again, the ONLY change here is an upgrade from Xcode 12 Beta 3 to XCode 12 beta 4, which just came out a couple days ago. Has anybody successfully used the AppsFlyer framework with Xcode 12 beta 4?

**Comment by dacoinminster** [comment]
I just discovered that AppsFlyer has a _beta_ version that is intended for use with iOS 14: https://support.appsflyer.com/hc/en-us/articles/360011451918#introduction

I tried the beta version this morning, but it has the same problem - cannot be used with XCode 12 Beta 4.

**Comment by dacoinminster** [comment]
Problem solved! Solution was posted on an Apple forum here: https://developer.apple.com/forums/thread/656509

Basically, search for ONLY_ACTIVE_ARCH and make sure it is YES everywhere.

**Comment by zchacker** [comment]
install the library via Swift Package Manager as described  in home page here : https://github.com/AppsFlyerSDK/AppsFlyerFramework
was solve the whole problem.
