### ISSUE TITLE
Unable to update framework

### ISSUE THREAD

**Issue by clapslock** [AppsFlyerSDK/AppsFlyerFramework#126]
# Report

## What did you do?

Run `carthage update --platform iOS --cache-builds`

## What did you expect to happen?

For the framework to update

## What happened instead?

An invalid json got returned

## Please provide any other relevant information.

I get `404: Not Found` when trying to fetch https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/AppsFlyerTracker.json

**Comment by wxmarek** [comment]
File removed https://github.com/AppsFlyerSDK/AppsFlyerFramework/commit/7fee3eadf05c6eedb9dbc55aa1313881f22a2084 :(

**Comment by wxmarek** [comment]
@af-fess please update .md5 for carthage

**Comment by pbartolome** [comment]
And what about versions lower than 5.3.0? the file "https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/AppsFlyerTracker.json" has been removed, and the new one only includes higher versions. Our Carthage update will fail trying to fetch 5.0.0, please restore that file or add the older versions to the new path.

The current Readme still says that for lower versions we should use the old json path "https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/AppsFlyerTracker.json"

**Comment by wxmarek** [comment]
@pbartolome same issue. I found workaround 
https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/5.1.0/AppsFlyerTracker.json

Select tag, find file and select RAW. Zip files from .json are still available.

**Comment by af-fess** [comment]
Merged the legacy versions:
https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/Carthage/appsflyer-ios.json
The [commit](https://github.com/AppsFlyerSDK/AppsFlyerFramework/commit/ba8eb78f6a49a14cb23de16da89cbbf3d46495bf)

**Comment by jbrennan** [comment]
I still think it’d be helpful to put the file back, as the `segment-appsflyer-sdk` at eg [version 5.2.0](https://github.com/AppsFlyerSDK/segment-appsflyer-ios/blob/5.2.0/Cartfile) still points to the old file location (this is what I use in my project). Now when I try to install via Carthage, it fails because that JSON file has moved in this repo.

**Comment by bixcorp** [comment]
Why moving json file in the repo? 😠 
You are breaking all CI integrations because you moved Carthage reference file.

**Comment by af-fess** [comment]
Thank you @bixcorp 

We restored the files. The new versions will be pointed to  
https://github.com/AppsFlyerSDK/AppsFlyerFramework/blob/master/Carthage/appsflyer-ios.json

The change is done to support Mac Catalyst
