### ISSUE TITLE
404 in Carthage link

### ISSUE THREAD

**Issue by chchrn** [AppsFlyerSDK/AppsFlyerFramework#127]
The links provided in the Readme returns a 404 error
`https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/AppsFlyerLib.json`
`https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/AppsFlyerTracker.json`

```
404: Not Found
```

**Comment by wxmarek** [comment]
look at https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/126

**Comment by af-fess** [comment]
Restored. For new versions - moved to Carthage/appsflyer-ios.json
