### ISSUE TITLE
6.0.2 does not have deviceLoggingDisabled

### ISSUE THREAD

**Issue by tsheaff** [AppsFlyerSDK/AppsFlyerFramework#128]
# Report

## SDK Version

`6.0.2`

ℹ Please replace these two lines with what you did.  
After upgrading from `5.1.0`, we followed [this guide](https://support.appsflyer.com/hc/en-us/articles/115001224823#ios-v600-beta-release-notes) you provided for renaming `AppsFlyerTracker.shared().deviceTrackingDisabled ` to `AppsFlyerLib.shared().deviceLoggingDisabled`

## What did you expect to happen?

To compile, with the same behavior as `deviceTrackingDisabled`

## What happened instead?

Did not compile

## Please provide any other relevant information.

This means we cannot confidently release for iOS 14, and looks like a mistake in your docs.

**Comment by af-fess** [comment]
You are right. Thank you for feedback. We changed this API to `anonymizeUser`. The DOC will be updated shortly.
