### ISSUE TITLE
Breaking change in patch build

### ISSUE THREAD

**Issue by billinghamj** [AppsFlyerSDK/AppsFlyerFramework#13]
You removed `handleOpenURL:sourceApplication:withAnnotaion:` with a patch version change. This is a breaking change and should really have been reserved for a major version change.

Could you try and keep to semver in the future please? It could have just been flagged as deprecated.

**Comment by golan19** [comment]
The typo in "withAnnotation" was fixed.

**Comment by billinghamj** [comment]
Indeed. That doesn't mean it wasn't a breaking change.

You removed a method which was being used, causing builds to break. As per semver, this should have been done with a major version bump.
