### ISSUE TITLE
Not updated documentation

### ISSUE THREAD

**Issue by InnaLabynskaya** [AppsFlyerSDK/AppsFlyerFramework#131]
# Report
Installation is not working for latest version, plz, update Documentation & add Changelog
Is is not obvious, what should be used instead of  
AppsFlyerLib.shared().trackAppLaunch() 
## SDK Version 6.0.3

ℹ Please replace these two lines with the sdk version.
e.g. via `4.11.0`

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Event to be tracked

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. No uninstalls on my dashboard

## Please provide any other relevant information.

ℹ Please replace these two lines with more information.
e.g. The issue started when we upgraded the plugin to the latest version

**Comment by AlexKarpov** [comment]
Same situation, but I have found [release notes](https://support.appsflyer.com/hc/en-us/articles/115001224823-AppsFlyer-iOS-SDK-Release-Notes#methods-added-removed-or-renamed) with api changes, and there was mentioned that `trackAppLaunch()` was renamed to `start()`

**Comment by InnaLabynskaya** [comment]
@AlexKarpov 
Thank you very much! It helps!

**Comment by 01000010x** [comment]
AppsFlyerFramework seems to be AppsFlyerLib
AppsFlyerFrameworkDelegate seems to be AppsFlyerLibDelegate

**Comment by af-fess** [comment]
The README moved to the official AppsFlyer site: https://github.com/AppsFlyerSDK/AppsFlyerFramework/commit/79694b506be931dd12f4ade3510f6eebef788bef

I very sorry your experience is less than perfect.

The link: https://support.appsflyer.com/hc/en-us/articles/207032066-iOS-SDK-V6-X-integration-guide-for-developers#introduction
