### ISSUE TITLE
Fuck you, your sdk and your analytics 

### ISSUE THREAD

**Issue by MadGeorge** [AppsFlyerSDK/AppsFlyerFramework#132]
The only reason i use this sdk is management requirements.  
Why the fuck if you invent breaking changes into new sdk release your github readme still presenting old api examples?  
I spent two hours after pod update to figure out why xcode can not resolve `AppsFlyerTracker.shared()`. And know what? It's not AppsFlyerTracker it's `AppsFlyerLib.shared()`.  
It was not enough crashes this sdk invent to our app in production, now this shit.  Go fuck yourself.

**Comment by af-fess** [comment]
I very sorry your experience is less than perfect.

Please, DM me with all the details of your ticket and inquiry and I'll make sure you get a quick reply.

We decided to move the README to the official AppsFlyer site that always up to date: https://support.appsflyer.com/hc/en-us/articles/207032066-iOS-SDK-V6-X-integration-guide-for-developers#introduction

The change:
https://github.com/AppsFlyerSDK/AppsFlyerFramework/commit/79694b506be931dd12f4ade3510f6eebef788bef
