### ISSUE TITLE
Mac Catalyst build error: Unable to find matching .xcframework slice

### ISSUE THREAD

**Issue by victorBaro** [AppsFlyerSDK/AppsFlyerFramework#134]
# Report

## SDK Version

ℹ Please replace these two lines with the sdk version.
AppsFlyerFramework-MacCatalyst `6.0.4`

## What did you do?

ℹ Please replace these two lines with what you did.  
Run `pod install`
Run/Archive for Release

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
Compilation to succeed

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
Compilation error

`No such module 'AppsFlyerLib'`

Useful warning:
warning: [CP] Unable to find matching .xcframework slice in '../Pods/AppsFlyerFramework-MacCatalyst/Mac Catalyst/AppsFlyerLib.xcframework AppsFlyerLib framework ios-x86_64-maccatalyst/AppsFlyerLib.framework ios-armv7_arm64/AppsFlyerLib.framework ios-i386_x86_64-simulator/AppsFlyerLib.framework' for the current build architectures (arm64 x86_64).

## Please provide any other relevant information.

ℹ Please replace these two lines with more information.
This error only appears when running in release mode. Debug mode compiles without errors.

**Comment by af-obodovskyi** [comment]
@victorBaro which Xcode version do you use?

**Comment by af-obodovskyi** [comment]
@victorBaro also, please mention what architecture settings do you use in your project [Project -> Build settings] and search for '`architectures`'.

**Comment by thefaj** [comment]
Broken here too—Xcode Beta 2.2 (which is needed to build for Apple Silicon). Not working on Intel or Apple Silicon DTK hardware.

**Comment by victorBaro** [comment]
@af-obodovskyi I am currently using Xcode 12.2 latest beta.
Architecture settings:
![Screen Shot 2020-10-19 at 22 51 13](https://user-images.githubusercontent.com/994334/96545691-b998f600-125d-11eb-8fdf-fd8f5b7c1e42.png)

**Comment by thefaj** [comment]
The company's silence on this issue means I'll recommend my clients remove the framework since it's no longer supported on iOS.

**Comment by obivanskiy** [comment]
@victorBaro After long investigation I have found out the solution, that might help out. Please, try to do the following Go to [Build Settings] -> search for "VALID_ARCH" and use  $(ARCHS_STANDARD). This solution might help out.

**Comment by victorBaro** [comment]
Thank you @obivanskiy for taking the time to check this.
I can't find "VALID_ARCHS" on Xcode 12.2 beta 4 RC. As posted before, I can only see "Architectures" which is already set for $(ARCHS_STANDARD) (both at target and project level).
Any other ideas?

**Comment by emreakcan** [comment]
@victorBaro  Search for architectures. But it didn't work for me
<img width="781" alt="Screenshot 2020-11-25 at 20 27 19" src="https://user-images.githubusercontent.com/29652273/100262009-9fd58780-2f5c-11eb-9a2b-ce09d98c89ed.png">

**Comment by Nekitosss** [comment]
Is any progress here? Still waiting for Catalyst support

**Comment by dhyani15** [comment]
I am facing a similar issue, Xcode version 12.4 architecture 
<img width="701" alt="Screenshot 2021-04-15 at 7 30 23 PM" src="https://user-images.githubusercontent.com/31188643/114882020-23ffad00-9e21-11eb-9774-153cc8945952.png">

**Comment by victorBaro** [comment]
Closing this since I was able to make it work. 
We are modularizing the app and I added Appsflyer as dependency in one of my internal packages and everything seemed to work
