### ISSUE TITLE
AppsFlyerFramework is not compatible with Xcode 12

### ISSUE THREAD

**Issue by harleyjcooper** [AppsFlyerSDK/AppsFlyerFramework#136]
# Report

## SDK Version

ℹ Please replace these two lines with the sdk version.
6.0.4

## Issue

Xcode 12 dropped support for iOS 8 as a deployment target, so it needs to be bumped to iOS 9.

**Comment by harleyjcooper** [comment]
I submitted https://github.com/AppsFlyerSDK/AppsFlyerFramework/pull/135 to address this.

**Comment by af-fess** [comment]
Doesn't make sense. AppsFlyer SDK is built with code 11.0. 
Xcode 12 is compatible with the SDKs. 
Please provide any errors if any.
