### ISSUE TITLE
Background urlsession crashes app in background

### ISSUE THREAD

**Issue by sorenzi** [AppsFlyerSDK/AppsFlyerFramework#14]
<BKProcessAssertion: 0x156527290> id: 6297-C307F39D-D800-4104-ACD5-665BD55C09B8 name: com.apple.nsurlsessiond.handlesession com.appsflyer.sdk process: <BKNewProcess: 0x1566464f0; com.outapp.identifier; pid: 6587; hostpid: -1> permittedBackgroundDuration: 30.000000 reason: backgroundDownload owner pid:6297 preventSuspend  preventThrottleDownUI  preventIdleSleep  preventSuspendOnSleep 

Steps to reproduce: (Version 4.3.8, Framework)
1. Background the app
2. Send multiple push notifications

Watch the device logs and see that a background task is not invalidated in time which cause iOS to terminate the app in the background

**Comment by RegisUplike** [comment]
Hi!

I have the same kind of crashes.
Did you find a fix or a workaround for this?

Thank you.

Régis.

**Comment by AppsFlyerGit** [comment]
@sorenzi @RegisUplike 
Thanks for your posts...
We already have fixes for that issue in version 4.4.1
Please update the version

**Comment by RegisUplike** [comment]
Hi, I am actually using the Unity framework and I have the crashes on iOS (I have open an issue on the Unity Git)
It seems that the Unity package doesn't include the 4.4.1 version of the iOS SDK. When do you plan to update the Unity package?

Thank you,
Régis.

**Comment by RegisUplike** [comment]
Hi,

I am actually using the Unity plugin that seems to contains the 4.3.9 version of the iOS framework.
When do you plan to update the Unity plugin?

Cheers,
Régis.
