### ISSUE TITLE
AppsFlyer 6.0.6 not available as latest release nor on Cocoapods (pushed 6.0.5, although 6.0.6 was briefly available)

### ISSUE THREAD

**Issue by Panajev** [AppsFlyerSDK/AppsFlyerFramework#140]
# Report

Hello @af-fess not sure if it is a problem under your control or not, but AppsFlyer 6.0.6 does not seem to be available as a Cocoapods update reliably and on this repository it does not appear as "Latest Release".

## SDK Version

6.0.5 - Cocoapods

## What did you do?

I tried to update the pod (updated the local pod spec repo and ran a pod update)

## What did you expect to happen?

AppsFlyer SDK to be updated to v6.0.6

## What happened instead?

The first time it did that, running the same process again downloaded 6.0.5.

## Please provide any other relevant information.

-

**Comment by af-fess** [comment]
In 6.0.6 we found a problem that can affect some clients (rare case).
 We decided to remove 6.0.6 from the pod and release a hotfix [6.0.7](https://github.com/AppsFlyerSDK/AppsFlyerFramework/releases/tag/6.0.7)
