### ISSUE TITLE
[Suggestion] remove +load method

### ISSUE THREAD

**Issue by shanksGuo** [AppsFlyerSDK/AppsFlyerFramework#141]
We are optimizing App's launch time, wo found that +load method in pre-main phase had a negative effect on launch, so we remove all +load in our code and significantly improved the launch experience.
But, We cannot remove +load in Applflyer framework. 
So, considering that Apple doest not encourage developer to use +load, I suggest AppsFlyer remove +load method. Instead, move the implement to AppsFlyer's "setup" method or Initialize.
Wish you accept my advice.

**Comment by af-fess** [comment]
Thank you, we will check it out

**Comment by shanksGuo** [comment]
Thanks, waiting for you to optimize it.

**Comment by shanksGuo** [comment]
@af-fess  Any progress?

**Comment by andr-ggn** [comment]
Upcoming `6.3.1` will contain such improvement
