### ISSUE TITLE
Xcode 12 + SPM 'IPA Processing Failed'

### ISSUE THREAD

**Issue by joshuapoq** [AppsFlyerSDK/AppsFlyerFramework#142]
## SDK Version
`6.1.0`

## What did you do?

_Note: We have a framework wrapping AppsFlyer and our SDK together. So we use AppsFlyerLib as a dependency of a dependency._

1. Used SPM to add `from: "6.0.8"` with Xcode 12.
2. Archived and went to distribute app (validate doesn't show the error).

## What did you expect to happen?

Should be fine.

## What happened instead?

Failed due to Xcode 12 issue with SPM where it embeds static frameworks when it shouldn't be doing this.

## Workaround

This is the same [issue as FirebaseAnalytics](https://github.com/firebase/firebase-ios-sdk/issues/6472). Whilst I don't share the same view that this is wholly and Xcode issue, there is a workaround and I would advise watching the previously linked issue.

To fix this:
1. Go to **Edit Scheme...**
2. Expand **Build**
3. Go to **Post-actions**
4. Press the **+** in the bottom left corner
5. Select your app from the dropdown for **Provide build settings from**
6. Add the following code (the plugins removal is optional - only needed if you have extensions)

```
rm -rf "${TARGET_BUILD_DIR}/${TARGET_NAME}.app/Frameworks/AppsFlyerLib.framework"
rm -rf "${TARGET_BUILD_DIR}/${TARGET_NAME}.app/Plugins/AppsFlyerLib.framework"
```

_Note: You can also give this script a nice name (by double tapping the name) but Xcode is a bit rubbish at editing it as the text goes invisible._

**Comment by andr-ggn** [comment]
https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/157
