### ISSUE TITLE
unable to track/log events 

### ISSUE THREAD

**Issue by TheSPST** [AppsFlyerSDK/AppsFlyerFramework#145]
# Report

## SDK Version

ℹ Please replace these two lines with the sdk version.
AppsFlyerFramework (6.1.1) 

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Event to be tracked

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. No uninstalls on my dashboard

## Please provide any other relevant information.

ℹ Please replace these two lines with more information.
e.g. The issue started when we upgraded the plugin to the latest version

**Comment by af-fess** [comment]
This issue has been inactive for a while, and will now be closed due to inactivity. If you still believe this is a valid issue, please feel free to reopen it or create a new issue with updated information.
