### ISSUE TITLE
Can't submit apps when adding the dependency using SPM

### ISSUE THREAD

**Issue by arturgrigor** [AppsFlyerSDK/AppsFlyerFramework#148]
# Report

## SDK Version

`6.1.2 via SPM`

## What did you do?

Added the dependency using SPM.

## What did you expect to happen?

Everything to work.

## What happened instead?

Couldn't submit my app using Xcode 12.3 (12C33). When I tried to submit the process failed with "Found an unexpected Mach-O header code: 0x72613c21"

## Please provide any other relevant information.

I managed to get it working by using the "Static Framework" option from https://support.appsflyer.com/hc/en-us/articles/207032066-AppsFlyer-SDK-Integration-iOS#integration

**Comment by andr-ggn** [comment]
https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/143

**Comment by MadsBogeskov** [comment]
+1

**Comment by Exey** [comment]
`Found an unexpected Mach-O header code: 0x72613c21`

**Comment by imervich-globant** [comment]
Did anyone fix this issue?

**Comment by atrinh0** [comment]
This might help: https://github.com/firebase/firebase-ios-sdk/issues/6472

**Comment by andr-ggn** [comment]
https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/157
