### ISSUE TITLE
How do I use AppsFlyerFramework Strict with carthage?

### ISSUE THREAD

**Issue by TimPapler** [AppsFlyerSDK/AppsFlyerFramework#149]
Hello,

I am trying to add strict version of AppsFlyerFramework to an app but can't find a URL for it. I added cocoapods just for this. 

Is there a way to get Carthage url for strict version of AppsFlyerFramework?

Thanks

**Comment by TimPapler** [comment]
Hello, 
actually getting an option to use strict version of AppsflyerFramework with SwiftPM would solve my issue as well. Since we are moving to SwiftPM.
Thanks

**Comment by andr-ggn** [comment]
https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/172 - SPM
For Carthage you can use `https://github.com/AppsFlyerSDK/AppsFlyerFramework/blob/master/Carthage/appsflyer-strict.json`
