### ISSUE TITLE
error: umbrella header does not include 'AppsFlyerDeepLinkObserver.h in 6.1.3

### ISSUE THREAD

**Issue by voidless** [AppsFlyerSDK/AppsFlyerFramework#152]
# Report

## SDK Version

`6.1.3`

## What did you do?

Built app in release mode

## What did you expect to happen?

Successful build

## What happened instead?

Build failed with error:
```
[15:34:23]: ▸ ❌  error: umbrella header for module 'AppsFlyerLib' does not include header 'AppsFlyerDeepLinkObserver.h'
[15:34:23]: ▸ ❌  /redacted/Modules/JRAppsFlyerStatisticsEngine/Source/AppsFlyerStatisticsEngine.swift:10:8: could not build Objective-C module 'AppsFlyerLib'
```

## Please provide any other relevant information.

Version 6.1.3 introduced a new header `AppsFlyerDeepLinkObserver.h`, but it was not added to the umbrella header.
Xcode requires that all public headers are added to the umbrella header of a framework.

**Comment by af-fess** [comment]
Good catch @voidless 💯 
This file is redundant here. I removed it manually https://github.com/AppsFlyerSDK/AppsFlyerFramework/commit/0b71b7a792e17e5f2a1b325a213c03a3fda18e7e.
Also removed from zip file for Carthage.

Please reload the framework because Cocapods saves it in the local cache
