### ISSUE TITLE
Support for Swift package manager

### ISSUE THREAD

**Issue by ashender** [AppsFlyerSDK/AppsFlyerFramework#157]
Support for Swift package manager was added for 6.1.0 only. The latest version is 6.1.4 and it doesn't support SPM. Please add support for it

**Comment by andr-ggn** [comment]
Hi, `6.1.4` supports SPM. 
Please, read https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/143 before.
I hope Xcode 12.5 will fix issue with static frameworks.

**Comment by zhongqing05** [comment]
use SPM
can't upload .and tip error.
Found an unexpected Mach-O header code: 0x72613c21

**Comment by meirkl** [comment]
@zhongqing05 I added this script to the archive post actions. Not sure what it does but I was able to upload to app store
```sh
# https://github.com/firebase/firebase-ios-sdk/issues/6472
LOGFILE="${ARCHIVE_PATH}/static-frameworks.log"
echo "Removing static frameworks from ${WRAPPER_NAME} archive" > $LOGFILE
find "${ARCHIVE_PRODUCTS_PATH}/Applications/${WRAPPER_NAME}" -name '*.framework' -print0 | while IFS= read -r -d '' fm; do
    name=$(basename "${fm}" .framework)
    target="${fm}/${name}"
    echo "Checking: ${fm}" >> $LOGFILE
    if file "${target}" | grep -q "current ar archive"; then
        rm -rf "${fm}"
        echo "Removed static framework: ${fm}" >> $LOGFILE
    fi
done
```

**Comment by andr-ggn** [comment]
6.3.0 does not require post actions. Thank you, guys, for your participation!
