### ISSUE TITLE
Undefined symbols on 4.4.1

### ISSUE THREAD

**Issue by nowudont** [AppsFlyerSDK/AppsFlyerFramework#16]
Hi AppFlyer team,

I was just adding my app with AppsFlyer 4.4.1 as a framework. After I added the framework to link Binary with Libraries, I run my app and I got following errors:

> Undefined symbols for architecture x86_64:
  "_SecItemAdd", referenced from:
      -[AppsFlyerKeychainWrapper setObject:withData:] in AppsFlyer(AppsFlyerKeychainWrapper.o)
     (maybe you meant: _fbdfl_SecItemAdd)
  "_SecItemCopyMatching", referenced from:
      -[AppsFlyerKeychainWrapper getObject:] in AppsFlyer(AppsFlyerKeychainWrapper.o)
     (maybe you meant: _fbdfl_SecItemCopyMatching)
  "_SecItemDelete", referenced from:
      -[AppsFlyerKeychainWrapper remove:] in AppsFlyer(AppsFlyerKeychainWrapper.o)
     (maybe you meant: _fbdfl_SecItemDelete)
  "_SecItemUpdate", referenced from:
      -[AppsFlyerKeychainWrapper update::] in AppsFlyer(AppsFlyerKeychainWrapper.o)
     (maybe you meant: _fbdfl_SecItemUpdate)
  "_kSecAttrAccessGroup", referenced from:
      -[AppsFlyerKeychainWrapper prepareForKeychain:] in AppsFlyer(AppsFlyerKeychainWrapper.o)
  "_kSecAttrAccessible", referenced from:
      -[AppsFlyerKeychainWrapper prepareForKeychain:] in AppsFlyer(AppsFlyerKeychainWrapper.o)
  "_kSecAttrAccessibleAlwaysThisDeviceOnly", referenced from:
      -[AppsFlyerKeychainWrapper prepareForKeychain:] in AppsFlyer(AppsFlyerKeychainWrapper.o)
  "_kSecAttrAccount", referenced from:
      -[AppsFlyerKeychainWrapper prepareForKeychain:] in AppsFlyer(AppsFlyerKeychainWrapper.o)
  "_kSecAttrGeneric", referenced from:
      -[AppsFlyerKeychainWrapper prepareForKeychain:] in AppsFlyer(AppsFlyerKeychainWrapper.o)
  "_kSecAttrService", referenced from:
      -[AppsFlyerKeychainWrapper prepareForKeychain:] in AppsFlyer(AppsFlyerKeychainWrapper.o)
  "_kSecClass", referenced from:
      -[AppsFlyerKeychainWrapper prepareForKeychain:] in AppsFlyer(AppsFlyerKeychainWrapper.o)
  "_kSecClassGenericPassword", referenced from:
      -[AppsFlyerKeychainWrapper prepareForKeychain:] in AppsFlyer(AppsFlyerKeychainWrapper.o)
  "_kSecMatchLimit", referenced from:
      -[AppsFlyerKeychainWrapper getObject:] in AppsFlyer(AppsFlyerKeychainWrapper.o)
  "_kSecMatchLimitOne", referenced from:
      -[AppsFlyerKeychainWrapper getObject:] in AppsFlyer(AppsFlyerKeychainWrapper.o)
  "_kSecReturnData", referenced from:
      -[AppsFlyerKeychainWrapper getObject:] in AppsFlyer(AppsFlyerKeychainWrapper.o)
  "_kSecValueData", referenced from:
      -[AppsFlyerKeychainWrapper setObject:withData:] in AppsFlyer(AppsFlyerKeychainWrapper.o)
      -[AppsFlyerKeychainWrapper update::] in AppsFlyer(AppsFlyerKeychainWrapper.o)

I've tried to clean & rebuild the project on xcode 7, but nothing changes. My app support for minimum OS 7.0.
Could you guys help me solve this issue ? 

Thank you.

**Comment by AppsFlyerGit** [comment]
@nowudont Add Security.framework in your Xcode project.
