### ISSUE TITLE
SDK logs clogging the console with debug data

### ISSUE THREAD

**Issue by crtgregoric** [AppsFlyerSDK/AppsFlyerFramework#160]
# Report

AppsFlyer is logging a huge amount of debug logs (`[DEBUG] AppsFlyer`) that are making the console saturated with AppsFlyer logs and making it hard to see other relevant information. I tried setting the `AppsFlyerLib.shared().isDebug ` flag to false, but didn't see any difference when doing do. This started happening quite recently, after a pod update.

This is a very frustrating issue, we have some important logs in the console that are now much harder to review.

Ideally there should be an option to tell the SDK to output only critical logs as errors and warnings.

## SDK Version
6.1.4

## What did you do?

Set the debug value to false.
`AppsFlyerLib.shared().isDebug = false`

## What did you expect to happen?

I expected to see less debug logs in the console.

## What happened instead?

I didn't notice any change in the amount of debug logs.

## Please provide any other relevant information.

SDK installed through CocoaPods as Segment.io integration:
`pod 'segment-appsflyer-ios'`

**Comment by af-fess** [comment]
you are right, good catch @crtgregoric 
https://github.com/AppsFlyerSDK/segment-appsflyer-ios/blob/master/segment-appsflyer-ios/Classes/SEGAppsFlyerIntegration.m#L24
we will fix it tomorrow.

**Comment by af-fess** [comment]
moved to https://github.com/AppsFlyerSDK/segment-appsflyer-ios/issues/49

**Comment by crtgregoric** [comment]
@af-fess Awesome, thx! :)
