### ISSUE TITLE
README screenshot project name "swidtTest" is typos ?

### ISSUE THREAD

**Issue by naijoug** [AppsFlyerSDK/AppsFlyerFramework#162]
README screenshot project name "swidtTest" is typos ?
`swiftTest` -- typos --> `swidtTest`?
![image](https://user-images.githubusercontent.com/5566978/108807989-905bee00-75e0-11eb-9925-98adb039871e.png)

**Comment by andr-ggn** [comment]
Thank you! We will update the information on GitHub
