### ISSUE TITLE
Releases notes

### ISSUE THREAD

**Issue by anthonyGuiguen** [AppsFlyerSDK/AppsFlyerFramework#164]
Hi 👋🏼
Please, can you add more transparency in your GitHub release notes ? 
Today, it's really difficult to understand what you do in a new version (features, issues, migration, context, critical or not, ...) and fill the historic.

Thanks !

**Comment by af-fess** [comment]
This is a release notes for iOS SDK: https://support.appsflyer.com/hc/en-us/articles/115001224823-AppsFlyer-iOS-SDK-release-notes
