### ISSUE TITLE
XCFramework Support

### ISSUE THREAD

**Issue by justinvallely** [AppsFlyerSDK/AppsFlyerFramework#165]
# Report

## SDK Version

6.2.3+

## What did you do?

Installation completed successfully.

## What did you expect to happen?

SDK installs as XCFramework

## What happened instead?

SDK installed as "fat" .framework

## Please provide any other relevant information.

With the introduction of M1 chips, Apple is shifting from "fat" frameworks to XCFrameworks and will soon require all packages to be shipped this way. Is this something AppsFlyer is actively working to support soon?

**Comment by S2Ler** [comment]
Please refer to this comment: https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/150#issuecomment-811078652. They are working on the fix.

**Comment by andr-ggn** [comment]
`pod 'AppsFlyerFramework', '6.3.0'`
