### ISSUE TITLE
Carthage support?

### ISSUE THREAD

**Issue by barfoon** [AppsFlyerSDK/AppsFlyerFramework#17]
Hello,

We are wondering if there is any way this library could be used with Carthage?

If we add this repo to our Cartfile, we see

```Failed to read file or folder at /private/var/folders/mt/xyqwwnr92dgbg8987kt45prr0000gn/T/carthage-archive.xJC5gC/__MACOSX/Carthage/Build/iOS/AppsFlyer.framework: Error Domain=com.antitypical.Result Code=0 "the DTSDKName key in its plist file is missing" UserInfo={com.antitypical.Result.function=readFailed, NSLocalizedDescription=the DTSDKName key in its plist file is missing, com.antitypical.Result.line=776, com.antitypical.Result.file=/tmp/carthage20160413-39362-hmnet1/Source/CarthageKit/Project.swift}```

Any help in getting the framework file generated for use with Carthage would be greatly appreciated. 
Cheers,

**Comment by AppsFlyerGit** [comment]
@barfoon Carthage support is in our plan,  ETA: 3-4 weeks.
Thanks.

**Comment by keab42** [comment]
Any update on this? It would be great to get Carthage support.

**Comment by af-golan** [comment]
@keab42 Have you tried it? its already done.

**Comment by vannip** [comment]
Hi, with the new 4.5.12 i can't use Carthage anymore...is Carthage support still available?

**Comment by af-golan** [comment]
@vannip please retry, should be fixed.

**Comment by vannip** [comment]
@af-golan it works now, thank you!

**Comment by dchakarov** [comment]
Hi, it doesn't seem to work with 4.6.5, can you take a look please?

**Comment by af-fess** [comment]
@dchakarov hey, Generally carthage located in https://github.com/AppsFlyerSDK/AppsFlyerFramework/releases  -> AppsFlyerTracker.framework.zip. Did you try to work with it?

**Comment by af-fess** [comment]
Please see opened ticket on Carthage side: https://github.com/Carthage/Carthage/issues/1782

Anyways now it should work
