### ISSUE TITLE
Question : How to install SDK in strict mode using SPM

### ISSUE THREAD

**Issue by sudeepdunzo** [AppsFlyerSDK/AppsFlyerFramework#172]
# Report

## SDK Version
via `6.2.6`

## What did you do?
Using SPM
File -> Swift Packages -> Add Package Dependency  -> https://github.com/AppsFlyerSDK/AppsFlyerFramework

## What did you expect to happen?

Ability to select strict mode SDK from the Package 

## What happened instead?

you can only install normal iOS SDK

## Please provide any other relevant information.

https://support.appsflyer.com/hc/en-us/articles/207032066#additional-apis-strict-mode-sdk

**Comment by sudeepdunzo** [comment]
hey any update on this ? is it already supported or is there a plan to add support for the same ?

**Comment by eshkoliGilad** [comment]
Hi @sudeepdunzo 

We are planning to add the Strict Mode SDK through SPM but it's currently still not available.
You can fetch the Strict Mode SDK only via CocoaPods or through the Carthage Dependency Manager as of now.

**Comment by TimPapler** [comment]
> hey any update on this ? is it already supported or is there a plan to add support for the same ?

It's silly but we have forked repo and added strict to package.swift and it seems to be working just fine, it's like near 0 effort.
All you need to do is: https://github.com/lakecoloring/AppsFlyerFramework/blob/e52a90d42310007c4a967ef07bcc4a0dbc54b3f9/Package.swift

**Comment by andr-ggn** [comment]
We have the same pull request
https://github.com/AppsFlyerSDK/AppsFlyerFramework/pulls

**Comment by andr-ggn** [comment]
Merged, tag will be added with next release. We have internal process in which 6.3.1 already in use. And I think in is not good practice to move 6.3.0 tag.
So please, use `master` branch when fetch library inside SPM
