### ISSUE TITLE
building for iOS, but linking in object file built for Mac Catalyst

### ISSUE THREAD

**Issue by Lishaoshuai** [AppsFlyerSDK/AppsFlyerFramework#173]
# Report

## SDK Version

ℹ Please replace these two lines with the sdk version.
6.3.0

## What did you do?

ℹ Please replace these two lines with what you did.  
change framework version 6.2.4 to 6.3.0
pod update AppsflyerFramework

## What did you expect to happen?

compile success

## What happened instead?

```
/Users/shaoshuaili/Library/Developer/Xcode/DerivedData/Coconut-gvlmxpzlbkjugbdlonnjkhkknloj/Build/Products/Debug-iphoneos/AppsFlyerLib.framework/AppsFlyerLib(AFSDKDevice.o), building for iOS, but linking in object file built for Mac Catalyst, file '/Users/shaoshuaili/Library/Developer/Xcode/DerivedData/Coconut-gvlmxpzlbkjugbdlonnjkhkknloj/Build/Products/Debug-iphoneos/AppsFlyerLib.framework/AppsFlyerLib' for architecture arm64
```

## Please provide any other relevant information.
nothing

**Comment by andr-ggn** [comment]
Update your CocoaPods to lates version
`sudo gem install cocoapods`

**Comment by Lishaoshuai** [comment]
cocoapods 1.9.3 failed
cocoapods 1.10.1 success
Thanks
