### ISSUE TITLE
Package Resolution Failed

### ISSUE THREAD

**Issue by cedavis12** [AppsFlyerSDK/AppsFlyerFramework#174]
# Report

## SDK Version

`6.3.0`

## What did you do?

Update package version from 6.2.6 to 6.3.0

## What did you expect to happen?

Xcode to resolve the `AppsFlyerFramework` package and successfully add the package to the project.

## What happened instead?

Xcode failed to resolve the package with a message that the there was an invalid custom path for the `AppsFlyerLib` target.

## Please provide any other relevant information.

The issue started when we upgraded the plugin to the latest version. See below for a screenshot of the error 
![Screen Shot 2021-05-28 at 10 29 15 AM](https://user-images.githubusercontent.com/23414116/120002252-a217ad80-bfa2-11eb-87bc-15cb58aba962.png)

**Comment by andr-ggn** [comment]
Try to clear SPM cache(~/Library/Caches/org.swift.swiftpm/) and DerivedData

**Comment by cedavis12** [comment]
That worked. Thank you!
