### ISSUE TITLE
[Xcode 12.5] App fails to build when linking to AppsFlyer 6.3.0

### ISSUE THREAD

**Issue by SergeyPetrovi4** [AppsFlyerSDK/AppsFlyerFramework#175]
**Report**

**SDK Version**
6.3.0

**What did you do?**
Update AppsFlyer via CocoaPod to last version (6.3.0)

**What did you expect to happen?**
Application to compile successfully

**What happened instead?**
App fails to build when linking to AppsFlyer 6.3.0. 
Error: "Appsflyer building for iOS, but linking in object file built for Mac Catalyst"

**Please provide any other relevant information.**
With version 6.2.6 app compile successfully

**Comment by andr-ggn** [comment]
https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/173
👆

**Comment by SergeyPetrovi4** [comment]
Understood. Thanks
