### ISSUE TITLE
Integration guide example code is tedious to read due to poor layout and code formatting

### ISSUE THREAD

**Issue by pepasibble** [AppsFlyerSDK/AppsFlyerFramework#178]
The [integration guide](https://support.appsflyer.com/hc/en-us/articles/207032066#integration) suffers from the combination of two poor design choices:

- Using a very narrow div to display source code (656 points wide):

<img width="2135" alt="Screen Shot 2021-06-07 at 4 27 55 PM" src="https://user-images.githubusercontent.com/78579108/121092373-0f9cb880-c7b1-11eb-9248-29ec7d5845f6.png">

- Formatting your source code with very long lines (the `didReceiveRemoteNotification` line is 200 characters wide):

<img width="1630" alt="Screen Shot 2021-06-07 at 4 51 21 PM" src="https://user-images.githubusercontent.com/78579108/121092384-13303f80-c7b1-11eb-8e6f-fce3e16fe853.png">

Either one is bad enough on its own, but good grief, please don't do both on the same page!

**Comment by af-fess** [comment]
Please, use a Dev hub: https://dev.appsflyer.com/hc/reference/api-reference-overview
