### ISSUE TITLE
Distribute xcframework via Carthage

### ISSUE THREAD

**Issue by CraigSiemens** [AppsFlyerSDK/AppsFlyerFramework#179]
Currently the Carthage json file only contain the `.framework` which doesn't work well with the simulator on M1 Macs. https://github.com/Carthage/Carthage/releases/tag/0.38.0 added support for distributing pre built xcframeworks.

It seems like it should be a pretty straight forward change to
- add the xcframeworks as artifacts on your releases
- add an `alt` url onto the existing url in the Carthage json files (instructions in carthage release notes)

**Comment by nomadplanet** [comment]
+1, yes please 🙏

**Comment by matheusalano** [comment]
+1

**Comment by alinfarcas12** [comment]
+1

**Comment by GZaccaroni** [comment]
+1

**Comment by MagFer** [comment]
+1

**Comment by tahadarendeli** [comment]
I hope the last PR should merged quickly. Clearly, it will help us a lot.

**Comment by af-fess** [comment]
As a temp solution, we will include https://github.com/AppsFlyerSDK/AppsFlyerFramework/pull/188 manually (this week). Our next step will be to include the flow to our release automation.

**Comment by cassianomonteiro** [comment]
Version 6.5.4 is not working. When trying to download the file below I get an error "not found".

https://github.com/AppsFlyerSDK/AppsFlyerFramework/releases/download/6.5.5/AppsFlyerLib.xcframework.zip

**Comment by amit-kremer93** [comment]
@cassianomonteiro thats because we don't have 6.5.5

**Comment by cassianomonteiro** [comment]
@amit-kremer93 6.5.4 is still not working. That version is listed on the carthage file definition, but then carthage fails fetching the latest version since that zip file is not available.

**Comment by af-fess** [comment]
@cassianomonteiro Can you please rebuild the project, the link workers properly: [from Carthage](https://github.com/AppsFlyerSDK/AppsFlyerFramework/blob/master/Carthage/appsflyer-ios.json#L67) - https://github.com/AppsFlyerSDK/AppsFlyerFramework/releases/download/6.5.4/AppsFlyerLib.xcframework.zip

and zip file exists: https://github.com/AppsFlyerSDK/AppsFlyerFramework/releases/tag/6.5.4

**Comment by CraigSiemens** [comment]
This should probably be a new issue. It's different from the original issue, the only similarity is that it's using Carthage.
