### ISSUE TITLE
Error on pod install activating strict mode from Podfile

### ISSUE THREAD

**Issue by rubenofen** [AppsFlyerSDK/AppsFlyerFramework#182]
# Report

## SDK Version
6.3.20

## What did you do?
I upgraded versión from 6.x.x to 6.3.20.
- changeMode.sh have dissapeared
- I've added 
  ```use_frameworks!
  $RNAppsFlyerStrictMode=true

- After that I've executed pod install and one error have been raised

## What did you expect to happen?

Install appsFlyer in strict mode for kids

## What happened instead?

An error have been raised during pod install:
```
[!] CocoaPods could not find compatible versions for pod "AppsFlyerFramework/Strict":
  In Podfile:
    react-native-appsflyer (from `../node_modules/react-native-appsflyer`) was resolved to 6.3.20, which depends on
      AppsFlyerFramework/Strict (= 6.3.2)

None of your spec sources contain a spec satisfying the dependency: `AppsFlyerFramework/Strict (= 6.3.2)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by amit-kremer93** [comment]
Hi @rubenofen, try to remove the plugin completely, add it again and run `pod install`.
Next time please open the issue in the [React-Native Appsflyer repo](https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin)
