### ISSUE TITLE
AppsFlyerLib Crashed in Jailbreaked Device

### ISSUE THREAD

**Issue by manunite** [AppsFlyerSDK/AppsFlyerFramework#183]
Hi. I'm a private developer using AppsFlyerLib.
A crash of AppsFlyerLib has recently been discovered on an Jailbreaked device.
The crash logs found in Crashlytics are as follows.

```
Crashed: com.apple.NSURLSession-delegate
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000020

__71-[AppsFlyerLib callServerWithEventName:eventValues:options:completion:]_block_invoke_3.1024 + 1006840
__60-[AppsFlyerLib __executeRequestWithEvent:completionHandler:]_block_invoke_3 + 1022664
__51-[AppsFlyerHTTPClient sendEvent:completionHandler:]_block_invoke.136 + 931672
__126-[AppsFlyerHTTPClient requestWithURL:URLRequest:HTTPMethod:dictionary:retries:isReturnJSON:isSharedSession:completionHandler:]_block_invoke + 928144
```

I wonder if there's a possibility of a problem with the Jailbreaked device.

**Comment by eshkoliGilad** [comment]
Hi, it looks like an issue with NSURLSession and may not be directly related to the AppsFlyer SDK. 
We also need to know which SDK version you are using, if it happens on non-Jailbroken devices and what it the rate of this crash.

Please open a support ticket with all the information you can supply and we will be more than glad to assist you.

**Comment by manunite** [comment]
Thank you for your confirmation.
I am using AppsflyerSDK 6.3.0.
It also occurs in devices that do non-Jailbroken device, but rarely occurs.
More than 99 percent of cases occur in Jailbroken device.

The logic for using Appsflyer in iOS is as follows.
1. Set appsFlyerDevKey and appleAppID in didFinishLaunchingWithOptions in AppDelegate.swift.
2. Call AppsFlyerLib start in applicationDidBecomeActive.

Thanks.

**Comment by eshkoliGilad** [comment]
Thank you for your response.
Please contact us at support@appsflyer.com so we can better assist you.

**Comment by manunite** [comment]
I sent an e-mail.
Check please.
Thank you for your help

**Comment by lake-taling** [comment]
I got same crash. How can i resolve it?

**Comment by lake-taling** [comment]
@ge-af Could you help me for about this issue?

**Comment by ge-af** [comment]
Hi @lake-taling 

Please contact us at support@appsflyer.com so we can better assist you.
You can also add more details and most importantly the full stack trace of the crash so we can see if this is indeed the same case or something else.
