### ISSUE TITLE
validateAndLogInAppPurchase returns 21003 error

### ISSUE THREAD

**Issue by kkarunakaran** [AppsFlyerSDK/AppsFlyerFramework#185]
# Report

## SDK Version
6.3.2

## What did you do?

triggered in app purchase

## What did you expect to happen?
Receipt validation success

## What happened instead?

`AppsFlyer: 
[Validate] Dictionary:{
    environment = Sandbox;
    status = 21003;
}
[Validate] Response Info:{
    data = <7b22656e 7669726f 6e6d656e 74223a22 53616e64 626f7822 2c227374 61747573 223a3231 3030337d>;
    dataStr = "{\"environment\":\"Sandbox\",\"status\":21003}";
    retries = 0;
    statusCode = 200;
    taskIdentifier = 7;
}
[Validate] Error: (null)
AppsFlyer_Unity_v6.3.2 didFinishValidateReceiptWithError called with {"status":21003,"environment":"Sandbox"}`

## Please provide any other relevant information.

I passed the in-app shared secret as additionalParameters

**Comment by ge-af** [comment]
Hi @kkarunakaran 

Are you trying to validate a one-time consumable in-app purchase or a subscription? 
This method is not working with subscriptions, we are working on a new feature for this one.

If that's indeed a one-time consumable in-app you are trying to validate, please contact us at support@appsflyer.com and we will be more than happy to provide help!

**Comment by leearmstrong** [comment]
Any update on supporting subscriptions via this method at all?

**Comment by af-fess** [comment]
`validateAndLogInAppPurchase` does not support any type of Subscription. AppsFlyer SDK uses https://github.com/AppsFlyerSDK/appsflyer-unity-purchase-connector. This feature could be activated over the AppsFlyer Dashboard.
