### ISSUE TITLE
No such module 'AppsFlyerLib' when file is open

### ISSUE THREAD

**Issue by williamkey123** [AppsFlyerSDK/AppsFlyerFramework#194]
# Report

## SDK Version

6.4.2

## What did you do?

Open a file that imports AppsFlyerLib or add "import AppsFlyerLib" to a Swift file.

## What did you expect to happen?

No errors

## What happened instead?

Xcode displays an error "No such module 'AppsFlyerLib'". However it continues to build properly, I'm just constantly seeing the error while the file is open and being edited.

<img width="547" alt="Screen Shot 2021-11-29 at 10 29 48 AM" src="https://user-images.githubusercontent.com/5880915/143925014-992cd80a-89cf-44db-8de3-da736ecc4b72.png">

## Please provide any other relevant information.

Installed via Cocoapods, with `use_frameworks!` on.

**Comment by af-fess** [comment]
This issue has been inactive for a while, and will now be closed due to inactivity. If you still believe this is a valid issue, please feel free to reopen it or create a new issue with updated information.
