### ISSUE TITLE
Freeze during AppsFlyer initialization

### ISSUE THREAD

**Issue by ee-piotrpluta** [AppsFlyerSDK/AppsFlyerFramework#197]
# Report

## SDK Version

`6.5.1`

## Environment

`iOS 15 / 15.1, any iOS Device, Xcode 13`

## What did you do

1. Integrated AppsFlyer with our app via Cocopods
2. Installed and started the app
3. App freezes during AppsFlyer initialization (first call of `AppsFlyerLib.shared()`). It is eventually killed by the OS.

**• After 3 subsequent launches the freeze stops occurring and the app launches normally.**

Stack traces for the main and other thread at the moment of the freeze:
<img width="342" alt="Screenshot 2022-01-10 at 13 43 06" src="https://user-images.githubusercontent.com/26298619/148906526-107ea1e3-f70b-4dc6-b008-8ee93a9c867e.png">
<img width="370" alt="Screenshot 2022-01-10 at 13 43 19" src="https://user-images.githubusercontent.com/26298619/148906536-18504185-44f2-4c63-97f4-a730f61d3f2c.png">

## Please provide any other relevant information.

• Manual AppsFlyer framework integration also yields the same results.
• Freeze happens both on Debug (via XCode) and AdHoc installations
• Adding Appsflyer to fresh (empty) project works without any problems.

**Comment by ge-af** [comment]
Hi @ee-piotrpluta ,
Thank you for reaching out to us!

To provide optimal support, we would kindly ask you to submit a support ticket to support@appsflyer.com.
When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information.
