### ISSUE TITLE
Callback to delegate method onConversionDataSuccess takes a lot of time

### ISSUE THREAD

**Issue by apurvverma7** [AppsFlyerSDK/AppsFlyerFramework#199]
The callback to _onConversionDataSuccess_ taking around 7-8 seconds. This is hindering the internal application flow.

App launch time: 1643791005.786339
Callback time: 1643791011.668103

Difference: about 6s

SDK Version - 6.5.2

AppsFlyerLib delegate in AppDelegate is set in the beginning, so I'm sure this is not the issue.

Is there a way around this?

**Comment by mirhadiali** [comment]
> The callback to _onConversionDataSuccess_ taking around 7-8 seconds. This is hindering the internal application flow.
> 
> App launch time: 1643791005.786339 Callback time: 1643791011.668103
> 
> Difference: about 6s
> 
> SDK Version - 6.5.2
> 
> AppsFlyerLib delegate in AppDelegate is set in the beginning, so I'm sure this is not the issue.
> 
> Is there a way around this?

I am also facing this issue if the app is already running when clicking on deep link it redirects to the app but onConversionDataSuccess is taking too much time.
