### ISSUE TITLE
ATS not supported

### ISSUE THREAD

**Issue by ashevin** [AppsFlyerSDK/AppsFlyerFramework#2]
After upgrading to 3.3.1 and running on iOS 9.1 beta, I see the following log messages:

`AppsFlyer Connection failed! Error - The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.`

**Comment by Bejil** [comment]
Try to add this to your info.plist file.
```
<key>NSAllowsArbitraryLoads</key>
<true/>
```

Or upgrade to appsflyer 3.3.3

**Comment by ashevin** [comment]
v3.3.3 does not solve the issue.

    2015-11-04 08:54:03.281 XXXXXX-iPhone beta[4778:3173794] AppsFlyer SDK version 3.3.3 started
    2015-11-04 08:54:05.901 XXXXXX-iPhone beta[4778:3173930] AppsFlyer Connection failed! Error - The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.

**Comment by Bejil** [comment]
It's working in two of my apps. I simply add NSAllowsArbitraryLoads : YES to all my info.plist (app, notificationCenter extension, and watchKit extension).

**Comment by Bejil** [comment]
Just, don't know if the two are different but I don't get the sdk from github but from this page :
https://support.appsflyer.com/entries/25458906-New-iOS-SDK-With-New-API-and-Get-Referral-Attribution-Data-Functionality

**Comment by ashevin** [comment]
It's no trick to work with ATS if you disable ATS for your app.  I could also add a specific exemption for AppsFlyer, but there should be no need.  AppsFlyer should update their code to use HTTPS in a way that doesn't require (blanket) exemptions.

**Comment by golan19** [comment]
@ashevin: V3.3.3 was built with the latest Xcode version 7.1, all the links are HTTPS.
Are you using Xcode beta? If so, can you try building with the formal Xcode version?

**Comment by ashevin** [comment]
I am running Xcode 7.1, App Store version (7B91b).

**Comment by Bejil** [comment]
Is XXXXXX-iPhone beta the name of your app ?

**Comment by ashevin** [comment]
Mostly.  I censored it.  The X's represent the censored part.

**Comment by Bejil** [comment]
Ok, so sorry I can't help you :( AppsFlyer is running well for me.

BTW, is Appsflyer using AfNetworking ? If so, be careful. It appears that their swizzling method is wrong. It can be conflictual with other sdk using it too.
