### ISSUE TITLE
Better changelog

### ISSUE THREAD

**Issue by PabloLerma** [AppsFlyerSDK/AppsFlyerFramework#20]
I just open this issue so the AppsFlyers's developers could modify the current and future releases so we can know what is getting fixed/done in every release.

Of course the changelog in the comments of your [support wiki](https://support.appsflyer.com/hc/en-us/articles/207032066-AppsFlyer-SDK-Integration-iOS) it is far from enough for a developer looking for what changed in that specific version.

**Comment by AppsFlyerGit** [comment]
Guys, you can find out the change log here:
https://support.appsflyer.com/hc/en-us/articles/207032066-AppsFlyer-SDK-Integration-iOS

**Comment by PabloLerma** [comment]
@AppsFlyerGit Where is the change log?

**Comment by PabloLerma** [comment]
@AppsFlyerGit as you can see in my first comment I already saw your change log in a Oriel Kaniel comment but as I said I think it is not good enough for a developer who has to figure it out what really changed in that version apart "Bug fixes and maintenance".

In example, the 4.5.0 iOS version it is not in that changelog and that version has the tracking uninstalled app feature.

I'm just asking to improve the way that you're publishing your changelog.

**Comment by AppsFlyerGit** [comment]
You can find the whats new in the version. we keep this repo for cocoapods  & carthage.
We are not committing any code here.

**Comment by PabloLerma** [comment]
Just as you said, you're committing your releases here so it could be good to have a more centralized place to watch the releases notes even if it is in your website. Also it could be better more information than "Bug fixes and maintenance" (AppsFlyer just broke our tracking 3 times with these versions).

But it's your product, obviously do as you wish :)

**Comment by AppsFlyerGit** [comment]
@PabloLerma point taken, wdym by broke your tracking? is it fixed now? do you still have issues?

**Comment by PabloLerma** [comment]
We already spoke with user support and it is not fixed, we just had to downgrade from 4.5.2 to 4.4.8 and it is working now but we're really sad that we had to downgrade.

**Comment by PabloLerma** [comment]
Every time it was for something with your SDK or our integration with you. But our code is really basic and you've already checked it and it seems okay but as you SDK is closed we don't know if you're swizzling and another 3rd party framework is colliding with you.

**Comment by AppsFlyerGit** [comment]
@PabloLerma we are not using swizzling..
You are saying that 4.5.2 is not working for you? which application?

**Comment by PabloLerma** [comment]
[Fever](https://itunes.apple.com/es/app/fever-los-mejores-planes-tu/id497702817?mt=8)

**Comment by PabloLerma** [comment]
http://support.appsflyer.com/hc/requests/44863

**Comment by AppsFlyerGit** [comment]
@PabloLerma saw the ticket.. can you refer to the requests by our support?

**Comment by PabloLerma** [comment]
Done!

**Comment by AppsFlyerGit** [comment]
Thanks. We will soon answer in the ticket it self.
