### ISSUE TITLE
Strict Mode SPM Support

### ISSUE THREAD

**Issue by BergQuester** [AppsFlyerSDK/AppsFlyerFramework#200]
Need to deprecate Carthage on our project and move to SPM. Unfortunately the strict mode version doesn't  appear to have SPM support

# Report

## SDK Version

ℹ Please replace these two lines with the sdk version.
via `6.5.2`

## What did you do?

Using SPM
File -> Swift Packages -> Add Package Dependency -> https://github.com/AppsFlyerSDK/AppsFlyerFramework

## What did you expect to happen?

Ability to select strict mode SDK from the Package

## What happened instead?

you can only install normal iOS SDK

## Please provide any other relevant information.

https://dev.appsflyer.com/hc/docs/install-ios-sdk

**Comment by OlegEremenko991** [comment]
Hello, I cannot resolve AppsFlyer package in Xcode 13.3:
`artifact not found for target 'AppsFlyerLib-Strict'`

**Comment by amit-kremer93** [comment]
you need to fetch strict version rom this repo:
https://github.com/AppsFlyerSDK/AppsFlyerFramework-Strict
