### ISSUE TITLE
Apps flyer missing some assets

### ISSUE THREAD

**Issue by lilidotshi** [AppsFlyerSDK/AppsFlyerFramework#201]
# Report

## SDK Version

6.5.4

## What did you do?

Ran "Update to latest packages" within Xcode using SPM

## What did you expect to happen?

I expected  AppsFlyerLib-Strict.xcframework.zip  to exist for download.

## What happened instead?
I got an error saying 

`failed downloading 'https://github.com/AppsFlyerSDK/AppsFlyerFramework/releases/download/6.5.2/AppsFlyerLib-Strict.xcframework.zip' which is required by binary target 'AppsFlyerLib': /Users/lilishi/Developer/Client-iOS/DerivedData/Mojo/SourcePackages/artifacts/AppsFlyerLib-Strict/AppsFlyerLib-Strict.xcframework.zip:404`

## Please provide any other relevant information.

Looking in releases, that file is indeed missing.

ℹ Please replace these two lines with more information.
e.g. The issue started when we upgraded the plugin to the latest version

**Comment by amit-kremer93** [comment]
We fixed it. Please check again
