### ISSUE TITLE
Why not support desktop native sdk?

### ISSUE THREAD

**Issue by toby20130333** [AppsFlyerSDK/AppsFlyerFramework#207]
Hi:

I want to dev desktop app with Qt,so can you support native c++ sdk? or plan to ? or how do i work with those sdks?

**Comment by toby20130333** [comment]
hello？

**Comment by toby20130333** [comment]
/?????? some body?

**Comment by amit-kremer93** [comment]
We're sorry, but we currently don't offer support Qt.
