### ISSUE TITLE
Link to SDK installation on readme points to an invalid page

### ISSUE THREAD

**Issue by sanimudah** [AppsFlyerSDK/AppsFlyerFramework#224]
# Report

## SDK Version

Current

## What did you do?

Click on link in readme.md.
<img width="896" alt="Screenshot 2023-01-10 at 10 01 12" src="https://user-images.githubusercontent.com/108250459/211445028-c3ddd854-234f-416c-9e07-af372fadaa4e.png">

## What did you expect to happen?

The link opens a page on AppsFlyer website with instructions to use the SDK

## What happened instead?

The link open shows `The page you are looking for doesn't exist`

<img width="1010" alt="Screenshot 2023-01-10 at 10 01 21" src="https://user-images.githubusercontent.com/108250459/211445052-f3651600-0b7c-440f-be4a-9e6805fbacee.png">

## Please provide any other relevant information.

The link should be updated to a correct link.

**Comment by amit-kremer93** [comment]
https://github.com/AppsFlyerSDK/AppsFlyerFramework/pull/205
