### ISSUE TITLE
`didResolveDeepLink` is not called on fresh app install but does work on subsequent UDL openings

### ISSUE THREAD

**Issue by dannyhertz** [AppsFlyerSDK/AppsFlyerFramework#226]
# Report

## SDK Version

6.9.1

## What did you do?

Fully followed UDL integration implementation for iOS https://dev.appsflyer.com/hc/docs/unified-deep-linking-udl-1

## What did you expect to happen?

didResolveDeepLink to be called with the correct DL data on fresh app install.

## What happened instead?

didResolveDeepLink is not being called on new app install openings but it does work on future cold/warm starts of the app via UDL.

**Comment by amit-kremer93** [comment]
👋 Hi @dannyhertz and Thank you for reaching out to us.
In order for us to provide optimal support, please submit a ticket to our support team at [support@appsflyer.com](mailto:support@appsflyer.com).
When submitting the ticket, please specify:
✅ your AppsFlyer sign-up (account) email
✅ app ID
✅ production steps
✅ logs
✅ code snippets
✅ and any additional relevant information.
