### ISSUE TITLE
Not able to add to multiple targets when installing via SPM

### ISSUE THREAD

**Issue by shanezzar** [AppsFlyerSDK/AppsFlyerFramework#229]
# Report

## SDK Version

ℹ via all

## What did you do?

ℹ Installed using SPM

## What did you expect to happen?

ℹ Should show in embedded frameworks/libraries 

## What happened instead?

ℹ Not showing when adding embedded frameworks/libraries  

## Please provide any other relevant information.

ℹ The package is poorly coded and built, please update to industry standards

**Comment by amit-kremer93** [comment]
@shanezzar thank you for your feedback. will update soon

**Comment by amit-kremer93** [comment]
related to this https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/227
