### ISSUE TITLE
handleOpenUrl:sourceApplication:withAnnotation crashes since conversion to swift 3

### ISSUE THREAD

**Issue by ldiqual** [AppsFlyerSDK/AppsFlyerFramework#23]
Integrated via cocoapods 1.0.1:

```
pod 'AppsFlyerFramework', '4.5.3'
```

The following line in our app crashes:

```
appsFlyerTracker.handleOpen(url, sourceApplication: sourceApplication, withAnnotation: annotation)
```

Since the conversion of our project to swift 3, the `annotation` parameter is exposed as `Any` and we get the following crash when opening a very basic url such as `appscheme://`: http://crashes.to/s/117e166d3ee

```
-[AppsFlyerTracker handleOpenURL:sourceApplication:withAnnotation:]

Fatal Exception: NSInvalidArgumentException
-[_SwiftValue objectForKey:]: unrecognized selector sent to instance 0x156119320
```

Passing `nil` to the `annotation` parameter fixes the issue.

It's worth noting that `handleOpenURL:sourceApplication:withAnnotation:` is deprecated since iOS 9 in favor of https://developer.apple.com/reference/uikit/uiapplicationdelegate/1623112-application

**Comment by af-golan** [comment]
@ldiqual Thanks for the info..
We will look into it.

**Comment by af-golan** [comment]
Added the new openUrl method, will be released on V 4.5.7

**Comment by ldiqual** [comment]
@af-golan Is the crash itself fixed? Or is it just about adding a new method? Nothing in the release notes :/

**Comment by ro-yhh** [comment]
I also encountered this problem today.
