### ISSUE TITLE
Status code failure: 403 when trying to integrate AppFlyer

### ISSUE THREAD

**Issue by rezuantpr** [AppsFlyerSDK/AppsFlyerFramework#231]
# Report

## SDK Version

`6.10.0`

## What did you do?

Here my steps how I am trying to integrate AppsFlyer (via cocoapods):

I insert this two lines in `didFinishLaunchingWithOptions` method:

```
    AppsFlyerLib.shared().appsFlyerDevKey = "key" 
    AppsFlyerLib.shared().appleAppID = "id"
```

Then I call 'start' inside the `applicationDidBecomeActive` method like this:
```
AppsFlyerLib.shared().start(completionHandler: { (dictionary, error) in
      if (error != nil) {
        print(error ?? "")
        return
      } else {
        print(dictionary ?? "")
        return
      }
    })


```
## What did you expect to happen?

I expect that my previous steps is enough to integrate

## What happened instead?

I see this error (from 'AppsFlyerLib.shared().start' completion:

**Error Domain=com.appsflyer.sdk.network Code=50 "Status code failure: 403" UserInfo={NSLocalizedDescription=Status code failure: 403}**

## Please provide any other relevant information.

I don't use the `SceneDelegate` file

appsFlyerDevKey I get from Configuration > App Settings > SDK authentication

My plan: Growth

**Comment by andr-ggn** [comment]
Wrong authentication. Double check your devkey and appid. If it will not work - send to andrii.h@appsflyer.com your appId
