### ISSUE TITLE
Provided Dynamic SDK is Static instead

### ISSUE THREAD

**Issue by mikechout** [AppsFlyerSDK/AppsFlyerFramework#233]
# Report

## SDK Version

`6.10.1`

## What did you do?

download `xcframework` from https://github.com/AppsFlyerSDK/AppsFlyerFramework/releases

## What did you expect to happen?

xcframework should be dynamic

## What happened instead?

xcframework is static

<img width="1292" alt="截圖 2023-04-20 上午11 48 09" src="https://user-images.githubusercontent.com/105188491/233253581-9175a42c-5db1-4877-8493-0ee4f18a8079.png">

## Please provide any other relevant information.

Seems like the `xcframework` file in the repo is `dynamic` but file downloaded from releases are `static`.

**Comment by andr-ggn** [comment]
No, by default AppsFlyer provides static framework. If you want to get dynamic - you can download it from `https://github.com/AppsFlyerSDK/AppsFlyerFramework/tree/master/Dynamic`

**Comment by mikechout** [comment]
Got it Thanks for your reply.
