### ISSUE TITLE
'AppsFlyerLib/AppsFlyerLib.h' file not found

### ISSUE THREAD

**Issue by jesphinpt** [AppsFlyerSDK/AppsFlyerFramework#238]
'AppsFlyerLib/AppsFlyerLib.h' file not found in the Xcode 14.2 with m1 machine which is in arm64 arch. 

AppsFlyerLib version is 

<img width="688" alt="Screenshot 2023-05-17 at 12 26 51 PM" src="https://github.com/AppsFlyerSDK/AppsFlyerFramework/assets/67142639/42066c3a-d978-4fdd-b0a4-d0cedd53c47a">

**Comment by 1008k** [comment]
i have the same problem.
AppsFlyer version is 6.12.0. (Occurs in other previous versions as well)
