### ISSUE TITLE
crash waitForATTUserAuthorizationWithTimeoutInterval unrecognized selector sent to instance

### ISSUE THREAD

**Issue by meanreaksmey** [AppsFlyerSDK/AppsFlyerFramework#239]
hi could you help check why after I add AppsFlyerLib.shared().waitForATTUserAuthorization(timeoutInterval: 60)
I got error:
-[AppsFlyerLib waitForATTUserAuthorizationWithTimeoutInterval:]: unrecognized selector sent to instance 0x12bd0c580
<img width="926" alt="Screenshot 2023-05-18 at 10 34 25 AM" src="https://github.com/AppsFlyerSDK/AppsFlyerFramework/assets/19529052/089fcb38-70ce-42ca-966c-eb72c59434e7">

**Comment by andr-ggn** [comment]
Why did you call `start()` on didFinishLaunchingWithOptions and delay(250ms) looks really weird

**Comment by meanreaksmey** [comment]
Hi @andr-ggn and @amit-kremer93, I see it crash while I using this version: AppsFlyerLib-Strict 6.12.0

**Comment by meanreaksmey** [comment]
now I fixed this issue by using version: AppsFlyerLib 6.11.0
