### ISSUE TITLE
Framework Not Found when archiving

### ISSUE THREAD

**Issue by wahyusumartha** [AppsFlyerSDK/AppsFlyerFramework#24]
Hi there, 

i have a problem when archiving with version above 4.5.1, (version 4.5.1 works like a charm).  
it always said framework not found, but it runs well when build or run the project, 

is there any work around that i need to do to avoid that problem ? 

Thanks, 

PS: i was installing via cocoapods, 

pod 'AppsFlyerFramework' (failed when archiving - version 4.5.6 installed) 
pod 'AppsFlyerFramework', '4.5.1' (all good)

**Comment by gustavogervasio** [comment]
I have the same problem.

**Comment by af-golan** [comment]
Thanks, should be ok, please run pod update
