### ISSUE TITLE
No release notes 6.11.1

### ISSUE THREAD

**Issue by bddq** [AppsFlyerSDK/AppsFlyerFramework#241]
# Report

## SDK Version

6.11.1

2 weeks later, I didn't find any release notes on https://support.appsflyer.com/hc/en-us/articles/115001224823#ios-sdk-v6-release-notes

What's new?

Regards, Benoit.

**Comment by xinsight** [comment]
I only can tell you that `6.11.1` added the ability to no longer compile on Xcode 14.2 🙃

**Comment by af-obodovskyi** [comment]
@xinsight, please update the SDK to higher version, the issue should be gone
