### ISSUE TITLE
241 duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by Shogo175R** [AppsFlyerSDK/AppsFlyerFramework#242]
# Report

when i try to build my project in Xcode 14 i'm getting this error

## SDK Version

"version": "6.8.3",

## What did you do?

project builded in unity->open it on xcode 14 and then archived ( here i got the error )

## What did you expect to happen?

project to be archived

## What happened instead?

241 duplicate symbols for architecture arm64

duplicate symbol '_OBJC_METACLASS_$_AFSDKmacOSKeychain' in:
    /Library/Developer/Xcode/DerivedData/Unity-iPhone-dyfmdbuodqiouselowpnytsunsna/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/AppsFlyerFramework/Main/AppsFlyerLib.framework/AppsFlyerLib(AFSDKmacOSKeychain.o)
    /eng-unity/build/1_debug/Libraries/Plugins/iOS/AppsFlyer/libAppsFlyerLib.a(AFSDKmacOSKeychain.o)
ld: 241 duplicate symbols for architecture arm64

**Comment by amit-kremer93** [comment]
Please take a look in our Unity repo [here](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin) and check for solution
