### ISSUE TITLE
Significant Decrease in App install Events Tracked via AppsFlyer iOS SDK Integration with Facebook

### ISSUE THREAD

**Issue by polurezov8** [AppsFlyerSDK/AppsFlyerFramework#243]
# Report

## SDK Version
`6.10.1`

## What did you do?

There has been a substantial decrease in the number of App install events with `fb_mobile_first_app_launch` param being tracked accurately via the integration between AppsFlyer iOS SDK (version 6.10.1) and Facebook Business. This decrease in event tracking is negatively impacting the ability to measure app install performance accurately and analyze user acquisition campaigns effectively.

Background:

AppsFlyer iOS SDK (version 6.10.1) is being utilized to track app installs and other relevant events.
An integration has been established between AppsFlyer and Meta Ads, ensuring that the tracking data is transmitted correctly to Facebook Business.
The Facebook Business dashboard includes an "App Installs" chart, which is expected to display accurate information obtained from AppsFlyer.
Observation:
After analyzing the data, it has become evident that the number of App install events recorded in Facebook Business has experienced a significant drop. This decrease is inconsistent with the expected number of first app launches, raising concerns about the accuracy of event tracking.

## What did you expect to happen?

The App install event with `fb_mobile_first_app_launch` param , which represents the first launch of the app, should be tracked reliably by AppsFlyer iOS SDK and transmitted accurately to Facebook Business. This event is crucial for measuring user acquisition performance and optimizing advertising campaigns.

## What happened instead?

There has been a critical decrease in the number of fb_mobile_first_app_launch events tracked and displayed accurately in the Facebook Business dashboard. The observed decrease is not consistent with the app's actual user acquisition and installation rates.

## Please provide any other relevant information.

- The decrease in `fb_mobile_first_app_launch` events could impact the analysis and optimization of user acquisition campaigns, leading to inaccurate insights and suboptimal decision-making.

- There have been no recent changes or updates made to the AppsFlyer iOS SDK or the Facebook Business integration settings.
- It is recommended to investigate and resolve this issue promptly to restore accurate event tracking and reporting.

Given the significance of accurate data tracking for evaluating app performance and optimizing campaigns, I kindly request the AppsFlyer iOS SDK team to investigate and address this issue to ensure the seamless transmission of fb_mobile_first_app_launch events to Facebook Business.

Thank you for your attention to this matter, and I look forward to your prompt response and resolution.

**Comment by Danyalo** [comment]
Hello @polurezov8, could you share some info about this issue, like what was causing it and what did you do to solve it?
I didn't manage to find the info in Appsflyer docs or hear back from their team. Learning more about this problem would be invaluable to me.
