### ISSUE TITLE
Async logEvent never seem to finish while there is no internet connection when called

### ISSUE THREAD

**Issue by kevin-hv** [AppsFlyerSDK/AppsFlyerFramework#245]
# Report

## SDK Version

iOS `6.12.0`

## What did you do?

- Disable internet connection
- Tried to await on the throwing async version of logEvent

```swift
func logEvent(name eventName: String, values eventValues: [String : Any]?) async throws -> [String : Any]
```

## What did you expect to happen?

- To throw an error and finish

## What happened instead?

- For more than 10 minutes the the await was waiting on the async function to finish (maybe it is stuck forever, have only waited that long)

## Please provide any other relevant information.

6.12.0 iOS SDK.

**Comment by andr-ggn** [comment]
This is known limitation for now and we are working on it. As a workaround - do not use await for now.
In case if you want to repeat InApp due to connection issue – you don't need to do this. The SDK will send cached InApps on the next start() in case network appears
