### ISSUE TITLE
SPM is broken

### ISSUE THREAD

**Issue by beridzev-ppb** [AppsFlyerSDK/AppsFlyerFramework#248]
# Report

## SDK Version
via `6.12.0`

## What did you do?
Run `SPM`

## What did you expect to happen?

Successfully include dependency 

## What happened instead?

the link is broken, fetching of Packages is interrupting 

## Please provide any other relevant information.

<img width="699" alt="Screenshot 2023-07-13 at 13 35 30" src="https://github.com/AppsFlyerSDK/AppsFlyerFramework/assets/126552289/15f3b766-9e3f-4898-980b-6611b244c765">

**Comment by af-obodovskyi** [comment]
Please, check the latest answer here: #240
