### ISSUE TITLE
Specifying version tag 6.12.0 won't fetch the necessary files

### ISSUE THREAD

**Issue by MrkFrnndz** [AppsFlyerSDK/AppsFlyerFramework#250]
# Report

## SDK Version

`6.12.0`

## What did you do?
Specified github link for AppsFlyerFramework and tag using pods

## What did you expect to happen?
It should get all the necessary files that can be found on Pods folder

## What happened instead?
Attached photo below is the only files I got

<img width="578" alt="image" src="https://github.com/AppsFlyerSDK/AppsFlyerFramework/assets/20393912/65ee5875-b233-4fea-a972-be52fbc1b284">

## Please provide any other relevant information.
I also tried the previous version 6.2.5 and it works perfectly fine but not on the latest version specifically 6.11.0 and up

**Comment by amit-kremer93** [comment]
Im not sure i understand. Did you try to install the framework like this?
`pod 'AppsFlyerFramework',:git => 'https://github.com/AppsFlyerSDK/AppsFlyerFramework.git'`
or am i missing something?

**Comment by MrkFrnndz** [comment]
> Im not sure i understand. Did you try to install the framework like this? `pod 'AppsFlyerFramework',:git => 'https://github.com/AppsFlyerSDK/AppsFlyerFramework.git'` or am i missing something?

Yes @amit-kremer93, Already tried that one and didn't solve the issue. Although I already solved the issue doing this command.

$ arch -arm64 brew install llvm
$ sudo gem install ffi
$ pod cache clean --all 
*restart mac*
$ pod install --repo-update
