### ISSUE TITLE
Distribute AppsFlyer SPM as source instead of binaryTarget.

### ISSUE THREAD

**Issue by minuscorp** [AppsFlyerSDK/AppsFlyerFramework#252]
# Report

## SDK Version

AppsFlyerLib 6.11.0 iOS

## What did you do?

Export my SPM package as a binary.

## What did you expect to happen?

To be able to build an xcodeproject for the AppsFlyerLib

## What happened instead?

You cannot build an xcodeproject from a binaryTarget as is released by AppsFlyer.

## Please provide any other relevant information.

I'd like to request a full source AppsFlyer SPM package so I can distribute my package as a binary framework.

**Comment by minuscorp** [comment]
Any comment about this?

**Comment by af-obodovskyi** [comment]
@minuscorp AppsFlyerSDK is a closed-source library, we do not plan to distribute AppsFlyerLib with a source code.
