### ISSUE TITLE
Invalid conversionInfo data with sdk greater than 6.7.0

### ISSUE THREAD

**Issue by ivan-r** [AppsFlyerSDK/AppsFlyerFramework#253]
# Report

## SDK Version

6.8.0 up to latest

## What did you do?

When installing the app through a deferred deep link, the `conversionInfo` received on `func onConversionDataSuccess(_ conversionInfo: [AnyHashable: Any])` is not correct. 

## What did you expect to happen?

Conversion info data should contains `"af_status": "Non-Organic"`.

## What happened instead?

Conversion info data should contains `"af_status": "Organic"`.

## Please provide any other relevant information.

Example: after opening a link with some tests parameters (e.g https://xxxxxxx.onelink.me/xxxx?deep_link_value=value&deep_link_sub1=parameter).  We get the following conversionInfo dictionary

- With sdk 6.12.2

 ``` 
[
	"install_time": "2023-09-01 17:42:58.390",
	"af_message": "organic install",
	"is_first_launch": 1,
	"af_status": "Organic"	
] 
```

- With sdk 6.7.0
``` 
[
	"deep_link_value": "value",
	"af_sub2": null,
	"click_time": "2023-09-01 17:20:55.031",
	"af_cpi": null,
	"is_universal_link": null,
	"adset_id": null,
	"adgroup_id": null,
	"af_sub4": null,
	"af_siteid": null,
	"agency": null,
	"CB_preload_equal_priority_enabled": 0,
	"is_first_launch": 1,
	"retargeting_conversion_type": "none",
	"install_time": "2023-09-01 17:22:08.491",
	"is_retargeting": false,
	"orig_cost": 0,
	"af_click_lookback": "7d",
	"is_branded_link": null,
	"af_pmod_lookback_window": "1d"
	"adgroup": null,
	"af_status": "Non-organic",
	"af_sub5": null,
	"redirect_response_data": null,
	"match_type": "probabilistic",
	"adset": null,
	"http_referrer": null,
	"media_source": "None",
	"engmnt_source": null,
	"campaign": none,
	"is_incentivized": false,
	"campaign_id": null,
	"af_sub3": null,
	"deep_link_sub1": "parameter",
	"esp_name": null,
	"af_sub1": null,
	"iscache": 1,
	"cost_cents_USD": 0
] 
```

**Comment by af-obodovskyi** [comment]
@ivan-r if the issue, that you are facing is during development testing, please, add your device to allow list on the HQ dashboard and try again.

**Comment by xiaoxiaotudou** [comment]
do you solve this problem ?

**Comment by ivan-r** [comment]
@xiaoxiaotudou This is related to the new reinstall detection system introduced in 6.8. This can be configured or disabled in AppsFlyer control panel.
