### ISSUE TITLE
Has a reference to the deprecated Apple Search Ads iAd Attribution APIs

### ISSUE THREAD

**Issue by bhushanb02** [AppsFlyerSDK/AppsFlyerFramework#257]
I was using the version 6.11.1 and found following references for the iAd from the logs:

```
[AppsFlyerSDK] [com.appsflyer.serial] iAD: iSearchAdsDict is nil
[AppsFlyerSDK] [com.appsflyer.serial] [iAD]: Cached `Apple Search Ads`: No, ASA disable: 0

[AppsFlyerSDK] [com.apple.root.default-qos] Dynamically loaded library: iAd

[AppsFlyerSDK] [com.appsflyer.serial] [iAD]: Will send to attr: 1
Apple Search Ads: {
    "Version3.1" =     {
        "iad-attribution" = false;
    };
}

"af_iad_data":{"Version3.1":{"iad-attribution":"false"}}
```

Then I have updated the version to lastest 6.12.2 and still there are some references to iAd like:

```
[AppsFlyerSDK] [com.appsflyer.serial] iAD: iSearchAdsDict is nil
[AppsFlyerSDK] [com.appsflyer.serial] [iAD]: ASA disabled: No
[AppsFlyerSDK] [com.appsflyer.serial] [iAD]: Send Atttribution request
"af_iad_data":{"error":"ADClientErrorTrackingRestrictedOrDenied”}
```

In both the cases(version checks) I have only installed the app and check the logs. As per apple documentation here (https://developer.apple.com/documentation/iad/iad_changelog) these Apple Search Ads iAd Attribution APIs are deprecated long back ago. I also got a mail from apple regarding the use of these deprecated APIs saying "_Within the next two years, the iAd framework will be completely removed from iOS. When that happens, any app that contains iAd framework code, including from third-party SDKs, will no longer launch on iPhone and iPad. We encourage you to remove the iAd framework from your app as soon as possible."_. Can you please look into this? Let me know in case you need any more details.

**Comment by af-obodovskyi** [comment]
@bhushanb02 starting verison 6.10.1 AppsFlyer SDK no longer contains iAd framework implementation. Logs, that you had sent for 6.12.2 are deprecated and will be removed in the upcoming SDK verisons.
