### ISSUE TITLE
About iOS privacy manifest

### ISSUE THREAD

**Issue by ladmini** [AppsFlyerSDK/AppsFlyerFramework#260]
Apple announced at [WWDC23](https://developer.apple.com/videos/play/wwdc2023/10060/?time=457) that developers will need to declare the reasons for using these APIs in their app’s privacy manifest. 
The following link for your reference
[List of APIs that require declared reasons now available](https://developer.apple.com/news/?id=z6fu1dcu)
[Describing use of required reason API](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)
So what I want to know is that if our project integrates AppsFlyer, it should be necessary to provide such a list. Do you have any plans of this list?
Thank you very much！

**Comment by micahcharlesbrown** [comment]
We have the same concerns with our app, any updates on this? Thanks!

**Comment by lambda123254** [comment]
And also need signing for the xcframework as well.

**Comment by af-obodovskyi** [comment]
@ladmini , @micahcharlesbrown  we are planning to release version with Privacy Manifest in the nearest releases. 

@lambda123254 the next SDK release, which is 6.12.4 will include the signed binaries.
