### ISSUE TITLE
Add signature to the framework

### ISSUE THREAD

**Issue by jesus-mg-ios** [AppsFlyerSDK/AppsFlyerFramework#268]
# Report

## SDK Version

ℹ Please replace these two lines with the sdk version.
e.g. via `6.13.1`

## What did you do?
D
ℹ Please replace these two lines with what you did.  
Download framework from GitHub.

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. The framework must be signed

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
Is Not signed

## Please provide any other relevant information.

ℹ Please replace these two lines with more information.
e.g. https://developer.apple.com/documentation/xcode/verifying-the-origin-of-your-xcframeworks

Please signed it but being verifiable, that is to say not self signed.
https://www.wwdcnotes.com/notes/wwdc23/10061/

**Comment by morisgateno-appsflyer** [comment]
done - 6.14.0 SDK version.
