### ISSUE TITLE
We're also facing the same issue using IOS SDK.

### ISSUE THREAD

**Issue by MingYik** [AppsFlyerSDK/AppsFlyerFramework#269]
We're also facing the same issue using IOS SDK. 
didResolveDeepLink(_ result: DeepLinkResult) not being triggered if the app is suspended by the system. 

We would highly appreciate if the issue is fixed as soon as possible

_Originally posted by @EmmaVvv in https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/156#issuecomment-871236767_

**Comment by rostegozavr** [comment]
We're in the same situation.
Is there a solution?
