### ISSUE TITLE
Installing AppsFlyer-SDK 4.5.11 (was 4.5.10)

### ISSUE THREAD

**Issue by RichAppz** [AppsFlyerSDK/AppsFlyerFramework#27]
Hi Guys, You have an issue with your podspec repo.

We have updated pods today and have downloaded your 4.5.11 release, the following has been noticed:

1. 4.5.11 doesn't exist in the releases documentation
2. 4.5.10 which we had installed is no longer downloadable so had to revert to 4.5.9
3. The 4.5.11 build has severe issues, in that the header file and lib are zipped into file.zip!

Can you check this all out before others have issues.

Thanks

**Comment by af-golan** [comment]
@RichAppz Hi, thanks for the info.
Can you please switch and use pod 'AppsFlyerFramework' instead. 
The static lib is deprecated.
