### ISSUE TITLE
Publishing on Xcode 15.3

### ISSUE THREAD

**Issue by jaroshevskii** [AppsFlyerSDK/AppsFlyerFramework#272]
# Report

## SDK Version

6.13.1

## What did you do?

Publish app to TestFlight

## What did you expect to happen?

Success publish app

## What happened instead?

<img width="846" alt="Untitled" src="https://github.com/AppsFlyerSDK/AppsFlyerFramework/assets/72662383/aa82a0ac-92c6-429a-9b95-c371ac079152">

## Please provide any other relevant information.

Xcode 15.3, iOS 14.0

**Comment by af-obodovskyi** [comment]
https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/263#issuecomment-2020589166

**Comment by af-obodovskyi** [comment]
https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/263#issuecomment-2025679494
