### ISSUE TITLE
AppStoreConnect Warning about MinimumOSVersion

### ISSUE THREAD

**Issue by alpha-moisol** [AppsFlyerSDK/AppsFlyerFramework#274]
# Report

## SDK Version

6.13.2

## What did you do?

Uploaded app build with Appsflyer-Dynamic to AppStoreConnect

## What did you expect to happen?

Build is uploaded without warnings

## What happened instead?

Got email from AppStoreConnect stated
```
Although delivery was successful, you may want to correct the following issues in your next delivery. Once you've corrected the issues, upload a new binary to App Store Connect.

ITMS-90747: Architecture incompatible with MinimumOSVersion. The app bundle at '***.app/Frameworks/AppsFlyerLib.framework' specifies a MinimumOSVersion of '100.0' but contains a 32-bit architecture that is unsupported on iOS 12 and later.
```

**Comment by amit-kremer93** [comment]
Hi! did you follow the [instructions](https://github.com/AppsFlyerSDK/AppsFlyerFramework?tab=readme-ov-file#swift-package-manager)? did you try to use the static framework as well?

**Comment by alpha-moisol** [comment]
> Hi! did you follow the [instructions](https://github.com/AppsFlyerSDK/AppsFlyerFramework?tab=readme-ov-file#swift-package-manager)? did you try to use the static framework as well?

Hello. Yes, I followed the instructions, did not try static library, only interested in dynamic

**Comment by gooson** [comment]
same +1

**Comment by JDBONFOR** [comment]
Same error here!

**Comment by Mitesh-Tank** [comment]
Same error here! Does anyone have any suggestions for solving this issue?

**Comment by kamalk2** [comment]
I have been facing the same issue too. But this error occurs only in XCode 15.2. Everything is working fine in XCode 15.2. 

Faced similar issues with a couple of other famous libraries too like Firebase. But they fixed it with an update. Hoping to get the fix from AppsFlyer soon too. Thanks.

@Mitesh-Tank @JDBONFOR @rishatyakushev @gooson @alpha-moisol @amit-kremer93

**Comment by DenTelezhkin** [comment]
I would like to point out, that this is not a warning. This is a hard error, that prevents any build upload when using Xcode 15.3.

Xcode 15.2 uploads work fine for now.

![CleanShot 2024-04-04 at 14 12 18@2x](https://github.com/AppsFlyerSDK/AppsFlyerFramework/assets/853604/4ac60767-2093-43ae-86d0-90bfba5c60d0)

**Comment by alpha-moisol** [comment]
> I would like to point out, that this is not a warning. This is a hard error, that prevents any build upload when using Xcode 15.3.
> 
> 
> 
> Xcode 15.2 uploads work fine for now.
> 
> 
> 
> ![CleanShot 2024-04-04 at 14 12 18@2x](https://github.com/AppsFlyerSDK/AppsFlyerFramework/assets/853604/4ac60767-2093-43ae-86d0-90bfba5c60d0)
> 
> 

It's warning for me, I am using Xcode 15.3

**Comment by alpha-moisol** [comment]
Try to update the library to latest version

**Comment by DenTelezhkin** [comment]
We are using the latest version (6.13.2), installed via SPM.

**Comment by icecoffin** [comment]
It's an error when you use the https://github.com/AppsFlyerSDK/AppsFlyerFramework repo. https://github.com/AppsFlyerSDK/AppsFlyerFramework-Dynamic only produces a warning (haven't tried the static version).

**Comment by adamrushy** [comment]
Yep, having this error here as well. In fact, most dependencies will have this unless they set this inside the `Info.plist` file. Firebase & Facebook have both released fixes for this.

This is the last dependency which is blocking using Xcode 15.3 - it would be great to get some attention on this.

**Comment by alpha-moisol** [comment]
As I understand, we cannot stay on Xcode 15.2, as from May 1 2024 we need to provide PrivacyInfo manifest, so it's obligatory to use Xcode 15.3

**Comment by feef-Talk360** [comment]
Glad I found this thread - also seeing this as a hard error when uploading from Xcode 15.3.0 even when on 6.13.2. uploading from Xcode 15.2.0 resolves the issue.

I will be forced to simply remove AppsFlyer from future releases of my app if this isn't resolved once I'm forced to use Xcode 15.3. Hope y'all are prioritizing a fix for this.

**Comment by alpha-moisol** [comment]
Still got the same warning

```
ITMS-90747: Architecture incompatible with MinimumOSVersion. The app bundle at '***.app/Frameworks/AppsFlyerLib.framework' specifies a MinimumOSVersion of '100.0' but contains a 32-bit architecture that is unsupported on iOS 12 and later.
```

AppsFlyerFramework-Dynamic 6.14.0

**Comment by adamrushy** [comment]
> AppsFlyerFramework (this repository) have wrong checksum in Package.swift. Failed to resolve packages.

I had this problem @denysdanyliukboosters but it seems that we have to use either Static or Dynamic library with version >6.12.0 so you'll need to update this as well to get 6.14.0

**Comment by alpha-moisol** [comment]
@af-obodovskyi Can this issue be reopened, cause the initial issue wasn't resolved?
