### ISSUE TITLE
AppsFlyerLib does not match checksum specified by the manifest

### ISSUE THREAD

**Issue by andibeqiri** [AppsFlyerSDK/AppsFlyerFramework#276]
# Report

'AppsFlyerLib' (e3063f25dd58b242c31d1bc5761fcb96930539e8e4d0745c22df792ecbd455e0) does not match checksum specified by the manifest (d7fdf61996dacb7787506305b6c541197ede64fcc4528c41842d9a507bd1b94b)

## SDK Version

6.14.0

**Comment by andibeqiri** [comment]
https://github.com/AppsFlyerSDK/AppsFlyerFramework/pull/275

**Comment by andibeqiri** [comment]
Created this PR: https://github.com/AppsFlyerSDK/AppsFlyerFramework/pull/275

**Comment by amit-kremer93** [comment]
please use this repo: https://github.com/AppsFlyerSDK/AppsFlyerFramework-Static

**Comment by y-hashida** [comment]
@amit-kremer93 

Excuse me for interrupting.

There does not appear to be a `6.14.0` tag on https://github.com/AppsFlyerSDK/AppsFlyerFramework-Static.
So the following configuration fails.
```swift
dependencies: [
        // ... (snip) ...
        .package(url: "https://github.com/AppsFlyerSDK/AppsFlyerFramework-Static.git", from: "6.14.0"),
        // ... (snip) ...
    ],
```

Please add the 6.14.0 tag to https://github.com/AppsFlyerSDK/AppsFlyerFramework-Static.

**Comment by amit-kremer93** [comment]
@y-hashida try again please

**Comment by y-hashida** [comment]
@amit-kremer93 
Thank you so much.

We have confirmed the existence of tag 6.14.0!

However

```swift
// Error
dependencies: [
        // ... (snip) ...
        .package(url: "https://github.com/AppsFlyerSDK/AppsFlyerFramework-Static.git", from: "6.14.0"),
        // ... (snip) ...
    ],
```


```
Revision 19c1c5c476d431e381f35c8c99a2fe6435085207 for appsflyerframework-static remoteSourceControl https://github.com/AppsFlyerSDK/AppsFlyerFramework-Static.git version 6.14.0 does not match previously recorded value 935dd2a4122e04133c067cb43215888ec93f00fa
```

And strangely enough, tag 6.14.0 with `.branch` builds fine!

```swift
// OK
dependencies: [
        // ... (snip) ...
        .package(url: "https://github.com/AppsFlyerSDK/AppsFlyerFramework-Static.git", .branch("6.14.0")),
        // ... (snip) ...
    ],
```

Does the same problem occur on your end?

**Comment by qwer10023500** [comment]
Same issue with the -Static SDK v6.14.0

**Comment by JohnnyTriHa** [comment]
`xcodebuild: error: Could not resolve package dependencies:
  checksum of downloaded artifact of binary target 'AppsFlyerLib' (e3063f25dd58b242c31d1bc5761fcb96930539e8e4d0745c22df792ecbd455e0) does not match checksum specified by the manifest (d7fdf61996dacb7787506305b6c541197ede64fcc4528c41842d9a507bd1b94b)
  fatalError`

**Comment by af-obodovskyi** [comment]
fixed, please clear your SPM caches and try again.

**Comment by RonKliffer** [comment]
This still does not work, I get the same error as before

**Comment by gooson** [comment]
same issue

**Comment by qwer10023500** [comment]
The issue has not been solved

checksum of downloaded artifact of binary target 'AppsFlyerLib' (e3063f25dd58b242c31d1bc5761fcb96930539e8e4d0745c22df792ecbd455e0) does not match checksum specified by the manifest (d7fdf61996dacb7787506305b6c541197ede64fcc4528c41842d9a507bd1b94b)

<img width="367" alt="image" src="https://github.com/AppsFlyerSDK/AppsFlyerFramework/assets/15137068/2ae41d9b-2499-491d-b5a1-e47c0c4e3f30">

**Comment by avfrias-gbm** [comment]
I'm sorry I have to ask, have you fixed the issue? I'm still using the previous version because of this issue
