### ISSUE TITLE
checksum of downloaded artifact of binary target 'AppsFlyerLib' does not match checksum specified by the manifest

### ISSUE THREAD

**Issue by khurshedgulov** [AppsFlyerSDK/AppsFlyerFramework#278]
# Report

## SDK Version

6.14.0

## What did you do?

Updated to version 6.14.0

## What did you expect to happen?

Nothing wrong

## What happened instead?

Xcode failed to resolve checksum:
checksum of downloaded artifact of binary target 'AppsFlyerLib' (e3063f25dd58b242c31d1bc5761fcb96930539e8e4d0745c22df792ecbd455e0) does not match checksum specified by the manifest (d7fdf61996dacb7787506305b6c541197ede64fcc4528c41842d9a507bd1b94b)

## Please provide any other relevant information.

-

**Comment by af-obodovskyi** [comment]
@khurshedgulov please clear SPM cache and try again. The issue is fixed.

**Comment by Patrashkov** [comment]
Hi, 
I clear the cache and removed both org.swift.swiftpm
rm -rf ~/Library/Caches/org.swift.swiftpm
rm -rf ~/Library/org.swift.swiftpm

after that remove DriveData, clean build, run reset package cache, and every time get that error
when remove and add a package I get the message 
![Screenshot 2024-04-08 at 16 59 54](https://github.com/AppsFlyerSDK/AppsFlyerFramework/assets/18269516/f5e57aec-799c-46b1-9520-a85103d4145a)

when I delete AppsFlyerLib package my project runs without that issue
Any recommendations?

**Comment by Chevel** [comment]
Same as above for me ☝️
