### ISSUE TITLE
Podspec for version 4.5.9 is actually pointing to 4.3.9

### ISSUE THREAD

**Issue by igor-makarov** [AppsFlyerSDK/AppsFlyerFramework#28]
[Link to podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/AppsFlyer-SDK/4.5.9/AppsFlyer-SDK.podspec.json)

**Comment by af-golan** [comment]
Thanks, already fixed.
Please use: https://github.com/CocoaPods/Specs/blob/master/Specs/AppsFlyer-SDK/4.5.11/AppsFlyer-SDK.podspec.json

**Comment by igor-makarov** [comment]
Whoops! Foiled by lexicographic sort order! 😂
