### ISSUE TITLE
6.14.1 - AppStoreConnect error about MinimumOSVersion

### ISSUE THREAD

**Issue by gooson** [AppsFlyerSDK/AppsFlyerFramework#287]
# Report

## SDK Version

ℹ Please replace these two lines with the sdk version.
6.14.1 static 

## What did you do?
Archive and Upload 

## What did you expect to happen?

Build is uploaded without error

## What happened instead?

Invalid Bundle. The bundle KREAM Alpha.app/Frameworks/AppsFlyerLib.framework does not support the minimum OS Version specified in the Info.plist. (ID: 1e6208c6-e530-4c56-973c-dee12d2f2e5a)

## Please provide any other relevant information.

![스크린샷 2024-04-19 오후 1 54 44](https://github.com/AppsFlyerSDK/AppsFlyerFramework/assets/1947069/dd245239-e7fa-43af-a4f0-63920bab4e38)

**Comment by gooson** [comment]
dynamic is working.

**Comment by gooson** [comment]
close

**Comment by af-obodovskyi** [comment]
@gooson could you please answer following questions, in order I could help you?

1. On what platform do you experience the issue? 
2. With which Xcode version do you try to release?

**Comment by inderdeep-singh-zomato** [comment]
@af-obodovskyi - this is an issue with Xcode 15.3 when building for iOS. We were also facing similar issue with Firebase, but it was fixed here.
- https://github.com/firebase/firebase-ios-sdk/issues/12476#issuecomment-1991948810

**Comment by af-obodovskyi** [comment]
@inderdeep-singh-zomato we know about this issue and we had a workaround solution for it with `minimumOSVersion=100` in previous SDK releases. In 6.14.1, we have upgraded the build system and bumped minimum supported iOS version to 12. 
Do you experience the same problem with our SDK in version 6.14.1?

**Comment by inderdeep-singh-zomato** [comment]
@af-obodovskyi we're using `v6.12.2` in our project and faced this issue while submitting release to App Store. I saw this open issue and thought that it is not resolved on the latest version as well.

**Comment by af-obodovskyi** [comment]
@inderdeep-singh-zomato could you please try to upgrade to v6.14.1? I have tested it with Xcode 15.2 and Xcode 15.3 and for me the issue with minimumOSVersion was gone. Also, it resolved another issue with generation of Privacy report for apps, using Static AppsFlyerLib, if you build with Xcode 15.3 and higher.

**Comment by inderdeep-singh-zomato** [comment]
@af-obodovskyi we'll try this for our next release and get back. Thanks.

**Comment by galipMNL** [comment]
Any indication when AppsFlyer AdRevenue SDK will have the same fixes? It is the only one left at 16.3.x whereas the static library as the Purchase Connector are on 16.4.x where this issue seams to be resolved.

**Comment by TakuyaCel** [comment]
Hello,

We are getting the same issue on version 6.14.3 as well.
It seems like it is due to some problems on XCode 15.x, would it be possible to change the MinimumOSVersion of Info.plist to 100 as temporary solution like Firebase did?
https://github.com/googleads/swift-package-manager-google-mobile-ads/issues/62#issuecomment-1981219533

**Comment by TakuyaCel** [comment]
Hi,
Sorry what I meant is not to change the minimumOSVersion of AppsFlyerFramework, but asking to change by AppsFlyer side as a temporary fix.

**Comment by af-obodovskyi** [comment]
@TakuyaCel what AppsFlyer SDK SPM repository do you use? Basically, we have changed the `minimumOSVersion` to 100 for Static and Strict SPM packages starting 6.14.0.

**Comment by TakuyaCel** [comment]
@af-obodovskyi 
Hi,
We are using AppsFlyerLib.framework.zip which are in the following link.
https://github.com/AppsFlyerSDK/AppsFlyerFramework/releases/tag/6.14.3
Also verified that the `minimumOSVersion` of Static and Strict SPM packages has set to 100.

**Comment by mindgraffiti** [comment]
Hello 👋  

This is happening for my app as well. 

**Platform:** iOS 
**Xcode version:** 15.3
**Min. OS:** iOS 16 

Updating to `6.14.4` didn't remove the warning from ASC. The SDK's SPM repo used is: https://github.com/AppsFlyerSDK/AppsFlyerFramework/releases/download/6.14.4/AppsFlyerLib-Dynamic-SPM.xcframework.zip

**Comment by phukhanhlee** [comment]
Fixed in lastest AppsFlyerSDK

**Comment by Banck** [comment]
@af-fess @phukhanhlee it's not fixed in latest AppsFlyerSDK (6.15.3) version - AppsFlyerLib-Static-SPM.xcframework.zip https://github.com/AppsFlyerSDK/AppsFlyerFramework/releases/download/6.15.3/AppsFlyerLib-Static-SPM.xcframework.zip
