### ISSUE TITLE
typos in header file

### ISSUE THREAD

**Issue by athibaud** [AppsFlyerSDK/AppsFlyerFramework#29]
[typo 1](https://github.com/AppsFlyerSDK/AppsFlyerFramework/blob/master/AppsFlyerTracker.framework/Headers/AppsFlyerTracker.h#L34)
------

```h
#define AFEventOrderId                  @"af_order_id"
```

should be `AFEventParamOrderId`

```h
#define AFEventParamOrderId                  @"af_order_id"
```

[typo 2](https://github.com/AppsFlyerSDK/AppsFlyerFramework/blob/master/AppsFlyerTracker.framework/Headers/AppsFlyerTracker.h#L241)
------

```h
- (void) handleOpenUrl:(NSURL *) url options:(NSDictionary *)options;
```

should be `handleOpenURL` (URL in uppercase)

```h
- (void) handleOpenURL:(NSURL *) url options:(NSDictionary *)options;
```

**Comment by vamnar** [comment]
+1
