### ISSUE TITLE
SDK is making requests even if start is not called

### ISSUE THREAD

**Issue by kubamatula** [AppsFlyerSDK/AppsFlyerFramework#292]
# Report

It seems that the SDK does not honor not sending any data to Appsflyer, before running the `start` method, as described: https://dev.appsflyer.com/hc/docs/preserve-user-privacy-ios#send-data-only-after-the-user-opts-in

## SDK Version

`6.14.3`

## What did you do?

Open the app via Appsflyer universal link, and not call the `start` method of the SDK.

## What did you expect to happen?

I expected that the link would not be fully handled. That the network request to AppsFlyer servers would not be made, because the SDK was not started. And that the deepLink would not be resolved.

## What happened instead?

The SDK made network calls to appLovin server, and fully handled the universal link with deeplink.

## Please provide any other relevant information.

I expect the appsflyer SDK to not make any network calls before I call the `start` method. It happens in other scenarios as well, not only with deepLinking.

**Comment by amit-kremer93** [comment]
When the SDK resolve a deep link he doesn't sent any data the the server, he just receives the deep link data
