### ISSUE TITLE
Unable to install via cocoa pods with support for iOS 6.0

### ISSUE THREAD

**Issue by javierquevedo** [AppsFlyerSDK/AppsFlyerFramework#3]
Unable to install it via cocoa pods with support for iOS 6.0.
Your documentation states that indeed it supports iOS 6.0: https://support.appsflyer.com/entries/25458906-iOS-SDK-Integration-Guide-v3-3-x-New-API-

OSX Version: El Capitán (10.11).
Cocoa pods 0.38.2
**Pod file**
    platform :ios, 6.0'

    target 'abdd' do
         pod "AFNetworking", "~> 2.5"
        pod "JSONModel"
        pod "PDKTZipArchive"
        pod "GCDWebServer", "~> 3.2.7"
        pod "AppsFlyerFramework", "~> 3.3.1"
    end

**Error:**
*gem install cocoapods --pre

Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:

- `AppsFlyerFramework (~> 3.3.1)` required by `Podfile`

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:388:in `handle_resolver_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:69:in `rescue in resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:56:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:535:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:533:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:210:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:133:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:132:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:104:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
*
**Reason:**
Even though your documentation states that the framework works on iOS 6 and above, the podspecs says  7.0

  spec.platform     = :ios, '7.0'

Please correct your pod specs or the documentation of the SDK

**Comment by golan19** [comment]
Fixed - updated pod spec to 6.0
