### ISSUE TITLE
Your instructions for use in swift in your README.md file are incorrect.

### ISSUE THREAD

**Issue by stuckj** [AppsFlyerSDK/AppsFlyerFramework#30]
Your instructions say to:

`import AppsFlyer`

to use AppsFlyer in swift. This is incorrect. You need to:

`import AppsFlyerTracker`

since that is what you named your framework. That hung me up for a little bit, so it might be good to fix to avoid confusion for other developers.

**Comment by af-golan** [comment]
@stuckj can you add the link? where do you see import AppsFlyer?

**Comment by stuckj** [comment]
It's in your README.md file at the root of this repository. Which is what shows up on the main github page for this repository. I.e., here: https://github.com/AppsFlyerSDK/AppsFlyerFramework. Look at the second line from the bottom before the Changelog section.

**Comment by af-golan** [comment]
@stuckj Thanks, changed it.
