### ISSUE TITLE
Crash `unrecognized selector` for WaitForATTUserAuthorization with timeoutInterval

### ISSUE THREAD

**Issue by mattisssa** [AppsFlyerSDK/AppsFlyerFramework#306]
# Report

I'm calling the `AppsFlyerLib.shared().waitForATTUserAuthorization(timeoutInterval: 60)` as it showed in documentation in getting 
```
Thread 1: "-[AppsFlyerLib waitForATTUserAuthorizationWithTimeoutInterval:]: unrecognized selector sent to instance 0x10172fac0"
```

## SDK Version

`6.15.3`

## What did you do?

- Added the SDK to my app
- Implemented it exactly as shown in [the docs](https://dev.appsflyer.com/hc/docs/integrate-ios-sdk)
- Launching my app causes the `unrecognized selector` issue

## What did you expect to happen?

Launching without crash

## What happened instead?

Crash with `unrecognized selector` issue

**Comment by af-obodovskyi** [comment]
@mattisssa Hi, nice to meet you. What is the iOS version and Xcode version you are using?

**Comment by mattisssa** [comment]
> @mattisssa Hi, nice to meet you. What is the iOS version and Xcode version you are using?

xcode version is `Version 16.1 (16B40)`
And iOS version is the latest – `18.1`

**Comment by af-obodovskyi** [comment]
@rakshitharodrigo 

Sorry for making you wait for so long. 

Basically, the following APIs are not available in the Strict mode SDK and should not be used. 

```
#ifndef AFSDK_NO_IDFA
/**
 AppsFlyer SDK collect Apple's `advertisingIdentifier` if the `AdSupport.framework` included in the SDK.
 You can disable this behavior by setting the following property to YES
*/
@property(nonatomic) BOOL disableAdvertisingIdentifier;

@property(nonatomic, strong, readonly) NSString *advertisingIdentifier;

/**
 Waits for request user authorization to access app-related data
 */
- (void)waitForATTUserAuthorizationWithTimeoutInterval:(NSTimeInterval)timeoutInterval
NS_SWIFT_NAME(waitForATTUserAuthorization(timeoutInterval:));

#endif
```

@mattisssa if you use Strict mode SDK, please remove this code, this is not necessary for Strict mode. In other case, please reach me out here in the comments and we will investigate the issue.
