### ISSUE TITLE
Warnings are raised if you are using iOS 8

### ISSUE THREAD

**Issue by reidmain** [AppsFlyerSDK/AppsFlyerFramework#32]
Why is `- (void) handleOpenURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication __attribute__((deprecated));` deprecated?

If you are supporting iOS 8+ you HAVE to use this method which means you will always have a warning when you compile your app. If AppsFlyer officially supports iOS 8 then this method should not be deprecated. Or at the very least use the attribute flag to indicate that it is deprecated in iOS 9 and above http://nshipster.com/__attribute__/

**Comment by af-fess** [comment]
will be fixed in v4.8.1
Thanks,
