### ISSUE TITLE
failed to compile bitcode for AppsFlyerTracker

### ISSUE THREAD

**Issue by JoeFerrucci** [AppsFlyerSDK/AppsFlyerFramework#34]
Trying to export for Ad Hoc (Enterprise). Worked fine every time until I upgraded my `pod AppsFlyerFramework` from version `4.5.3` to `4.5.9` -- Once I updated the pod I started getting this error. I followed the instructions in the GitHub README, and also on the AppsFlyer iOS SDK website. Neither fixed the issue.

Again, this started when I upgraded from `4.5.3` to `4.5.9`

Dev environment: 
- Xcode 7.3.1
- Swift 2.3
- Cocoapods 0.39.0

```failed to compile bitcode for AppsFlyerTracker:
    Debug: SDK path: /Applications/Xcode7.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk
    Debug: PATH: ['/Applicat…
```

I downgraded back to `4.5.3` and rebuilt + export and it worked flawlessly. Then installed AppsFlyerFramework `4.5.9` again…still failed. 

If I disable `Rebuild using Bitcode` (not desirable) during the Ad Hoc export process it works fine.

**Comment by af-golan** [comment]
@JoeFerrucci please update to 4.5.12.
The issue is fixed.

**Comment by JoeFerrucci** [comment]
Thanks @af-golan -- is the README up-to-date?
