### ISSUE TITLE
error: Invalid bitcode version (Producer: '800.0.42.1_0' Reader: '703.0.31_0')

### ISSUE THREAD

**Issue by JoeFerrucci** [AppsFlyerSDK/AppsFlyerFramework#35]
Trying to Archive my project so that I can upload to AppStore and distribute Ad Hoc (Enterprise). Worked fine every time until I upgraded my `pod AppsFlyerFramework` from version `4.5.3` to `4.5.12` -- Once I updated the pod I started getting this error. I followed the instructions in the GitHub README, and also on the AppsFlyer iOS SDK website. Neither fixed the issue.

Again, this started when I upgraded from `4.5.3` to `4.5.12`

Dev environment: 
- Xcode 7.3.1
- Swift 2.3
- Cocoapods 1.1.1

```
error: Invalid bitcode version (Producer: '800.0.42.1_0' Reader: '703.0.31_0')
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I downgraded back to `4.5.3` and rebuilt + archive/export and it worked flawlessly. Then installed AppsFlyerFramework `4.5.12` again…still failed.

**Comment by af-golan** [comment]
@JoeFerrucci We used to build our FW with the latest Xcode, 
Can you try to build with Xcode 8.1?

**Comment by JoeFerrucci** [comment]
Nope, can't build with Xcode 8 @af-golan

**Comment by shoaibahmedqureshi** [comment]
@JoeFerrucci  Any luck with this issue ?
