### ISSUE TITLE
Can not open app directly in iOS10

### ISSUE THREAD

**Issue by carlosbdw** [AppsFlyerSDK/AppsFlyerFramework#37]
I tested both iOS9 and iOS10 devices , in iOS9 device the deeplinking works ,but it opens app store in iOS10 device.

**Comment by BenjaminAF** [comment]
In order for us to provide optimal support, we would kindly ask you to submit any issues to support@appsflyer.com

When submitting an issue please specify your AppsFlyer sign-up (account) email , your app ID , production steps, logs, code snippets and any additional relevant information.
