### ISSUE TITLE
pod spec use_frameworks dependency 

### ISSUE THREAD

**Issue by mateuszmackowiak** [AppsFlyerSDK/AppsFlyerFramework#40]
AppsFlyerFramework failes integrate with cocoapods if defined as a dependency of another spec. 
Using:
AppsFlyerFramework 4.6.1.
cocoapods 1.2.1.beta.1 (other versions also)

`[!] The 'Pods-SampleProject_Example' target has transitive dependencies that include static binaries: (/Example/Pods/AppsFlyerFramework/AppsFlyerLib.framework)`

**Comment by af-golan** [comment]
@mateuszmackowiak can you try with the latest 4.6.2 just published?

**Comment by mateuszmackowiak** [comment]
Same thing. But this maby a coapods error.

**Comment by mateuszmackowiak** [comment]
Hmm. i found this: https://github.com/CocoaPods/CocoaPods/issues/2926 it seam when i define 
```
pre_install do |installer|
      # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
      def installer.verify_no_static_framework_transitive_dependencies; end
end
```
in the podfile it works

**Comment by tirrorex** [comment]
@ml-golan why did you close an issue that still isn't fixed as off yet?
