### ISSUE TITLE
Reachability error

### ISSUE THREAD

**Issue by Serdg** [AppsFlyerSDK/AppsFlyerFramework#41]
Hello. I am installing your library and AppleReachability with pods
```
pod 'AppsFlyerFramework', '~> 4.6.1'
pod 'AppleReachability'
```
and have an error when compiling the project
```
duplicate symbol _OBJC_CLASS_$_Reachability in:
    .../AppleReachability/libAppleReachability.a(Reachability.o)
    .../AppsFlyerFramework/AppsFlyerLib.framework/AppsFlyerLib(Reachability.o)
```
How can I solve this problem?

**Comment by af-golan** [comment]
@Serdg please use the latest version, this issue is already fixed, thanks.

**Comment by Serdg** [comment]
@af-golan I am using the latest version
`Installing AppleReachability (5.0)Installing AppsFlyerFramework (4.6.1)`

**Comment by Serdg** [comment]
@af-golan Thank you
