### ISSUE TITLE
Library integration size is 2.5 mb?

### ISSUE THREAD

**Issue by rsaunders100** [AppsFlyerSDK/AppsFlyerFramework#47]
Just want to confirm that the framework will add 2.5mb to our app size?

If so how can we reduce this to an acceptable amount? (<1mb)

**Comment by af-fess** [comment]
@rsaunders100 hey, what do you use: Static Lib, static Framework or Cocoapods?

**Comment by af-fess** [comment]
2.5M comes because of 4 architectures it supports, device + simulator.
