### ISSUE TITLE
Add public_header_files to podspec

### ISSUE THREAD

**Issue by dmorrow** [AppsFlyerSDK/AppsFlyerFramework#49]
Please add a public_header_files node to the podspec, so that other apps can find the header files

**Comment by BenjaminAF** [comment]
In order for us to provide optimal support, we would kindly ask you to submit any issues to support@appsflyer.com

When submitting an issue please specify your AppsFlyer sign-up (account) email , your app ID , production steps, logs, code snippets and any additional relevant information.
