### ISSUE TITLE
Carthage only works with 4.7.2, does not work with 4.7.3

### ISSUE THREAD

**Issue by bsarrazin** [AppsFlyerSDK/AppsFlyerFramework#50]
After running `carthage bootstrap`, the binary for `4.7.3` is being downloaded but nothing is being extracted in `Carthage/Build/iOS/`. 

Reverting back to `4.7.2` has fixed the problem and files are being extracted as expected.

Xcode 8.3
Carthage 0.19.1

**Comment by af-fess** [comment]
@bsarrazin Solved, thank you
