### ISSUE TITLE
No information sent about the device on first app launch from non-organic install

### ISSUE THREAD

**Issue by elemeshko** [AppsFlyerSDK/AppsFlyerFramework#51]
Hello,
I'm experiencing the issue on a single device, but everything works fine on the rest of devices. The device is whitelisted.
Tested with AppsFlyer SDK version 4.5.12 and 4.7.3, the device's iOS version is 10.1.1.
I have tested the same case on a device with the same iOS version - everything is fine there, the problem appears only on a single device.

The AppsFlyer framework has been integrated using [this guide](https://support.appsflyer.com/hc/en-us/articles/207032096-Accessing-AppsFlyer-Attribution-Conversion-Data-from-the-SDK-iOS-Deferred-Deeplinking-).

The steps that lead to the issue are the following:

1. Paste the link with an ad-campaign to a browser.
2. The alert with a suggestion to open the App Store will appear. Choose "Open".
3. Install the app from the App Store and open it.
4. The logs that contain AppsFlyer's mention from the connected device are the following:

```
Apr 20 15:47:36 iPad-Pro-1011 AppName[1045] <Notice>: AppsFlyer SDK version 4.7.3 started build (541)
```

There is no mention that the device's information is sent to an AppsFlyer's server, neither no conversion data is received.

5.  Close the app and open it again The second launch of the app works fine and the logs are:

```
Apr 20 16:18:18 iPad-Pro-1011 AppName[1061] <Notice>: AppsFlyer SDK version 4.7.3 started build (541)
// Here comes a lot of logs about communication with AppsFlyer's servers.
Apr 20 16:18:18 iPad-Pro-1011 AppName[1061] <Notice>: AppsFlyer: sent information to server, status = 200
Apr 20 16:18:18 iPad-Pro-1011 AppName[1061] <Notice>: This is a none organic install. Media source: MediaSourceName
Campaign: CampaignName
```

In step 4 I'm expecting the same result like in step 5.
Why does this happen?

Thank you.

**Comment by BenjaminAF** [comment]
In order for us to provide optimal support, we would kindly ask you to submit any issues to support@appsflyer.com

When submitting an issue please specify your AppsFlyer sign-up (account) email , your app ID , production steps, logs, code snippets and any additional relevant information.
