### ISSUE TITLE
Dependency "AppsFlyerFramework" has no shared framework schemes

### ISSUE THREAD

**Issue by samweareloup** [AppsFlyerSDK/AppsFlyerFramework#63]
Added the dependency as mentioned in the readme using Carthage. Get the above error. Please help.

**Comment by TwiterZX** [comment]
Hi,
You are having this issue because you are referencing to a binary framework (no source code) like you would do to a regular one (with source code, that needs to be built).

In your Cartfile, you are probably using this line 
`github "AppsFlyerSDK/AppsFlyerFramework"`

You should use (one line):
`binary "https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/Carthage.json"`

Or this (pending validation by AppsFlyer Team)
`binary "https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/AppsFlyerTracker.json"`

**To AppsFlyer Team:**
Please update your doc to change Carthage integration instructions
Example doc to update:
https://support.appsflyer.com/hc/en-us/articles/207032066-AppsFlyer-SDK-Integration-iOS

**Comment by samweareloup** [comment]
Hi,

Yes we are using github "AppsFlyerSDK/AppsFlyerFramework" on the cart file.

But its definitely an issue with the 4.8.3 version. Because if I lock the
version to 4.8.2 with this line on car file.resolved: github
"AppsFlyerSDK/AppsFlyerFramework" "4.8.2"  then it builds without an error.

Also I tried using

binary "https://raw.githubusercontent.com/AppsFlyerSDK/
AppsFlyerFramework/master/Carthage.json"

But it gave the same error. It seems it is an issue with the version

Dependency "AppsFlyerFramework" has no shared framework schemes for any of
the platforms: iOS


If you believe this to be an error, please file an issue with the
maintainers at https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/new

SAMPATH DASSANAYAKE

SENIOR iOS ENGINEER

[image: Loup Signature]

/ Lvl 3, 13 Cremorne St, Cremorne VIC 3121
<https://maps.google.com/?q=13+Cremorne+St,+Cremorne+VIC+3121&entry=gmail&source=g>
 /

/ 0458 688 626 / weareloup.com /

**Comment by TwiterZX** [comment]
Hi @samweareloup 
It gave you the same error, because you probably did a `carthage bootstrap` that reads the lock file.
you should run `carthage update` (⚠️this will update all dependencies)

**Comment by samweareloup** [comment]
Hi Riad,

The issue is the error pops up pin the CI. Its Cricle CI and the issue is
its a fresh environment that is spun up every time.

What should I do there?

-Sam

SAMPATH DASSANAYAKE

SENIOR iOS ENGINEER

[image: Loup Signature]

/ Lvl 3, 13 Cremorne St, Cremorne VIC 3121
<https://maps.google.com/?q=13+Cremorne+St,+Cremorne+VIC+3121&entry=gmail&source=g>
 /

/ 0458 688 626 / weareloup.com /

**Comment by samweareloup** [comment]
And how is it that there is no errors when the version is locked to 4.8.2?

SAMPATH DASSANAYAKE

SENIOR iOS ENGINEER

[image: Loup Signature]

/ Lvl 3, 13 Cremorne St, Cremorne VIC 3121
<https://maps.google.com/?q=13+Cremorne+St,+Cremorne+VIC+3121&entry=gmail&source=g>
 /

/ 0458 688 626 / weareloup.com /

**Comment by andr-ggn** [comment]
Hello @samweareloup!
Are you sure that Cricle CI cleans all the environment? Maybe it caches something from Carthage? 
Also, it would be great if you provide an example from Cricle CI with a problem.

Thanks, @TwiterZX for your participation!

**Comment by samweareloup** [comment]
Hi,

Yes it does. It spins up a new VM and sets up the environment based on a
config file and Carthage.

Im still confused why it only fails when the version is 4.8.3. It works
with 4.8.2

Cheers,
Sam

SAMPATH DASSANAYAKE

SENIOR iOS ENGINEER

[image: Loup Signature]

/ Lvl 3, 13 Cremorne St, Cremorne VIC 3121
<https://maps.google.com/?q=13+Cremorne+St,+Cremorne+VIC+3121&entry=gmail&source=g>
 /

/ 0458 688 626 / weareloup.com /

**Comment by samweareloup** [comment]
Joao,
Please see Riad Krim's suggestion. That fixed it for me,
Sam

SAMPATH DASSANAYAKE

SENIOR iOS ENGINEER

[image: Loup Signature]

/ Lvl 3, 13 Cremorne St, Cremorne VIC 3121
<https://maps.google.com/?q=13+Cremorne+St,+Cremorne+VIC+3121&entry=gmail&source=g>
 /

/ 0458 688 626 / weareloup.com /

**Comment by borisyurkevich** [comment]
I would Kindly suggest to update [documentation](https://support.appsflyer.com/hc/en-us/articles/207032066-AppsFlyer-SDK-Integration-iOS) to reflect this.
