### ISSUE TITLE
Carthage JSON file is broken

### ISSUE THREAD

**Issue by greimers** [AppsFlyerSDK/AppsFlyerFramework#66]
Currently the binary dependency file for Carthage is broken as there is a typo in the JSON. (Closing quote missing in last line). Please update the file quickly.

--> [https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/AppsFlyerTracker.json](https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/AppsFlyerTracker.json)

This was introduced in https://github.com/AppsFlyerSDK/AppsFlyerFramework/commit/d9f84eb1bbebe14809c9d35922968ea3d2b0e922

**Comment by andr-ggn** [comment]
Sorry for that. Fixed
