### ISSUE TITLE
[Segment] [AppsFlyerFramework] Use Carthage

### ISSUE THREAD

**Issue by Ataraxiis** [AppsFlyerSDK/AppsFlyerFramework#67]
Hi !

I post this here can we can't create issues on https://github.com/AppsFlyerSDK/segment-appsflyer-ios

Is it possible to use Carthage to use `segment-appsflyer-ios` ? 

I was using Cocoapods but I want to switch to Carthage. 

Thank you,

**Comment by andr-ggn** [comment]
Hello, @Ataraxiis 

Unfortunately, for the time being, this is not in the plans. But we will take into account the wish
