### ISSUE TITLE
Crash on iOS  9.3.2 NSInvalidArgumentException

### ISSUE THREAD

**Issue by mrpuzzler** [AppsFlyerSDK/AppsFlyerFramework#68]
Fatal Exception: NSInvalidArgumentException
-[AppsFlyerRequestCache ForBackgroundURLSession:completionHandler:]: unrecognized selector sent to instance 0x12756b710
__99-[AppsFlyerHTTPClient sendRequestEventToServer:isRequestFromCache:appID:isDebug:completionHandler:]_block_invoke

**Comment by andr-ggn** [comment]
Hello, @mrpuzzler!

- SDK version?
- How often does crash occur? This happens regularly?
- Inside of `AppsFlyerRequestCache` there is no `ForBackgroundURLSession:completionHandler:`. In the place of `AppsFlyerRequestCache` instance, there must be another class containing the `ForBackgroundURLSession: completionHandler:` method. 

Most likely you have a memory leak. On our part, we can also check for leaks

**Comment by mrpuzzler** [comment]
Latest SDK. This is a single crash.

**Comment by andr-ggn** [comment]
My idea is to wait a little: If the crash will happen for other clients few more times, we will handle it. If it is a single crash, we will put it to backlog.

I will leave this ticket open for a while for other users to contribute if they will have the same problem

**Comment by mrpuzzler** [comment]
Yeah, sure.
