### ISSUE TITLE
Memory leaks reported after putting the app into the background

### ISSUE THREAD

**Issue by idcuesta** [AppsFlyerSDK/AppsFlyerFramework#7]
Hi,

I am profiling my app and I can see some memory leaks caused by AppsFlyer SDK when I put my app into the background.

They seem to be caused by the internal call ```[AppsFlyerTracker backgroundstatCall]``` than happens when the app is moved to the background

I am currently using version 3.3.3 of AppsFlyer SDK.

<h2>Steps to reproduce it</h2>
- Start running my app
- Put my app into the background
- Bring my app to the foreground
- Memory leaks appear

<h2>Screenshot</h2>
![screen shot 2015-11-16 at 11 10 48](https://cloud.githubusercontent.com/assets/2726409/11180551/65e07208-8c53-11e5-9694-08847badfba2.png)

**Comment by owlstack** [comment]
@idcuesta was this fixed for you? It's happening to me on Android!

**Comment by af-golan** [comment]
@owlstack this issue is talking about iOS, which was already fixed.
Which Android SDK version are you talking about? can you share more details?

**Comment by owlstack** [comment]
@af-golan : I reported the issue here: https://github.com/AppsFlyerSDK/XamarinAndroidBinding/issues/4

It's related to Xamarin Android SDK.
