### ISSUE TITLE
Possible memory leak of [AppsFlyerCrossPromotionHelper trackCrossPromoteImpression:campaign:]

### ISSUE THREAD

**Issue by abekert** [AppsFlyerSDK/AppsFlyerFramework#70]
There is a possible memory leak of **NSOperationQueue** object after calling
`[AppsFlyerCrossPromotionHelper trackCrossPromoteImpression:campaign:]`
A purple warning appears in the Memory Graph after calling this method.

Here are screens:

![](https://image.ibb.co/k1iwKd/Screen_Shot_2018_06_14_at_5_13_31_PM.png)

![](https://image.ibb.co/fdB5Cy/Screen_Shot_2018_06_14_at_5_13_37_PM.png)

![](https://image.ibb.co/fuOJXy/Screen_Shot_2018_06_14_at_5_07_39_PM.png)

Version: 4.8.4

**Comment by andr-ggn** [comment]
We don't have a method like `- processImpressionForAppId:campaign:`

**Comment by abekert** [comment]
I am very sorry 🙈, I've copied a wrong method name. Now it's fixed.

**Comment by andr-ggn** [comment]
We have found an issue. 4.8.7 will contain changes. Thank you.

**Comment by abekert** [comment]
Great news! Thank you, team.
