### ISSUE TITLE
How to get af_dp property from shortened onelink

### ISSUE THREAD

**Issue by insidegui** [AppsFlyerSDK/AppsFlyerFramework#73]
We have implemented onelink with universal links following the documentation. The documentation explains how to get attribution data and deferred deep link information from an install, but it doesn't explain how we can extract the `af_dp` property of a link in the case a user who's already got the app installed launches the app through onelink.

The delegate method is not called in that case and I couldn't find any information on how to get the data behind the shortened link using the SDK. We need to get our custom deeplink from the `af_dp` property of the shortened onelink in order to route the user to the appropriate place in the app.

**Comment by insidegui** [comment]
Yes, we are using universal links and everything works but we can't seem to find a way to get the `af_dp` parameter when a user opens up a shortened link and already has the app installed.

**Comment by insidegui** [comment]
But then the link won't open in the app, that's what the associated domains are for.

**Comment by Edudjr** [comment]
@insidegui if you have implemented deep links, the shortened link will redirect you to the af_dp, which should contain the deep link, and your app will intercept that :)

**Comment by josepbordesjove** [comment]
For me, if I don't have the associated domain, goes to safari evened if the af_dp is configured, the app does not intercept the link. Have you been able to solve this?

**Comment by Edudjr** [comment]
My bad, there is a problem indeed! I forgot to update here. The workaround is adding the af_ios_url with a supported universal link.

**Comment by gsc-dev** [comment]
Hi, do we have a proper solution for this? We are having the same issue and the workaround is not a good option for us as it breaks universal links and will impact our acquisition tracking.

**Comment by wesfieldj** [comment]
Hi,

First, in general, please contact support@appsflyer.com with all questions. AppsFlyer support will help you with all questions and issues.

For the solution to your questions, you will need to set up the OneLink to include the af_dp parameter on the AppsFlyer dashboard, under the link management section.
Then once the user clicks the short link and the app is opened then AppsFlyer SDK will make a call to the OneLink servers, and the OneLink servers will return the parameters of the short-link in the onAppOpenAttribution() method.
So you can retrieve the af_dp parameter from the link inside onAppOpenAttribution().

For example the link:
    https://aftestlink.onelink.me/U0S2/468fefbf
has the equivalent long link of:
    https://aftestlink.onelink.me/U0S2?pid=test&af_dp=redirectionHere%3A%2F%2F

When clicking on the link:
    https://aftestlink.onelink.me/U0S2/468fefbf, 
the app is opened and onAppOpenAttribution returns: 
[AnyHashable("link"): https://aftestlink.onelink.me/U0S2/468fefbf, AnyHashable("pid"): test, AnyHashable("af_dp"): redirectionHere://]

**Comment by Panajev** [comment]
hey @wesfieldj , thank you for the update, but the "af_dp" parameter is indeed set. The SDK is notified in the App Delegate method as instructed in the docs, but the onAppOpenAttribution / onConversionDataReceived (app started as a result of deeplink or app resumed as a result of the deeplink) delegate methods are not called by the SDK.

```
    public func onAppOpenAttribution(_: [AnyHashable: Any]!) {
        print("onAppOpenAttribution")
    }

    public func onAppOpenAttributionFailure(_ error: Error!) {
        print("onAppOpenAttributionError: \(error.localizedDescription)")
    }

    public func onConversionDataReceived(_: [AnyHashable: Any]!) {
        print("onConversionDataReceived...")
    }

    public func onConversionDataRequestFailure(_ error: Error!) {
        print("onAppOpenAttributionError: \(error.localizedDescription)")
    }
```

**Comment by gsc-dev** [comment]
Hi,

Why this issue has been closed? The bug still seems to be happening with no accepted solutions.

The steps provided @wesfieldj have already been applied and the problem still persists.

**Comment by wesfieldj** [comment]
@gsc-dev @Panajev 
Can you please open a ticket to AppsFlyer Support? 
Send an email to support@appsflyer.com with a description of your issue. 
We can continue to help you debug from a support ticket.
You can link this issue in the ticket and we will help you get it solved asap.

**Comment by namaxinan** [comment]
I leart it a hard way, `af_dp` only returns in payload if you Enable Re-Targeting Campaign Measurement
:
<img width="816" alt="screenshot 2019-03-03 at 12 44 36 pm" src="https://user-images.githubusercontent.com/45415833/53691102-443f8f80-3db2-11e9-970c-61ff4d44cdaf.png">

**Comment by BraveMatchstickMen** [comment]
@namaxinan you are right all their answers are suck. 

Does it work well for you? Although I have disabled the Re-Targeting Campaign Measurement, the onAppOpenAttribution / onConversionDataReceived delegate methods are not called.

**Comment by P0ed** [comment]
For me it only calls delegate methods if I call `tracker.trackAppLaunch()`. So as a workaround for already launched app you can call it again inside `continueUserActivity` func.

**Comment by ramikhafagi96** [comment]
I'm really surprised that this issue is still happening since 2018. I try to open the link when the app is not in the background, and when i open it, it doesn't deep link to the content in my app and it just takes me to the home screen.

**Comment by mqzkim** [comment]
I ran into this issue without knowing how my affiliate implemented this... 
I assumed that there is logic to execute deep link internally by parsing the `af_dp` query in onConversionDataReceived. 

When no query is used in the shortened link, parsing seems to work normally.
(ex. `https://something.onelink.me/{{ID}}/{{ShortenID}}` )

But when any query is put in, the af_dp query does not pass.
(ex. `https://something.onelink.me/{{ID}}/{{ShortenID}}?user_id={{USER_ID}}` )

Even if af_dp was directly added as a query, deep link execution did not work at all. 
(ex. `https://something.onelink.me/{{ID}}/{{ShortenID}}?user_id={{USER_ID}}&af_dp={{DEEP_LINK_URI}}` )

I searched the documentation and found an example using a parameter called link...
Final, It works!!
(ex. `https://something.onelink.me/{{ID}}/{{ShortenID}}?user_id={{USER_ID}}&link={{DEEP_LINK_URI}}` )
