### ISSUE TITLE
Update the restoration handler to silence swift 4.2 warning

### ISSUE THREAD

**Issue by dubemike** [AppsFlyerSDK/AppsFlyerFramework#76]
## Pre swift 4.2 
```swift 
    func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([Any]?) -> Void) -> Bool 
```
## swift 4.2 
``` swift
    func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool
```

With Swift 4.2 `restorationHandler` went from being `([Any]?) -> Void` to `([UIUserActivityRestoring]?) -> Void`, but AppsFlyerTracker still wants that old one. This generates a warining `Treating a forced downcast to ([Any]?) -> Void  as an optional will never produce nil`

**Comment by GLJeffery** [comment]
I got a crash in Crashlytics today on the line that does the downcast, first time seeing it and was in production release of the app, is it related?

AppDelegate.swift line 104
@objc AppDelegateapplication first-element-marker restorationHandler(_:_:_:)

code:
`AppsFlyerTracker.shared().continue(userActivity, restorationHandler: restorationHandler as! ([Any]?) -> Void)`

**Comment by GLJeffery** [comment]
Is this by chance related to

Version 4.8.10 - October 31, 2018

Fixed a race condition when continueUserActivity was invoked after applicationDidBecomeActive causing onAppOpenAttribution not to be called

**Comment by andr-ggn** [comment]
Hi @GLJeffery. Please pass `nil` instead of `restorationHandler as! ([Any]?) -> Void`

**Comment by andr-ggn** [comment]
@GLJeffery @dubemike 
[Here](https://support.appsflyer.com/hc/en-us/articles/207032066-AppsFlyer-SDK-Integration-iOS) we have this for Swift 4.2 
<img width="618" alt="screen shot 2018-11-22 at 16 08 19" src="https://user-images.githubusercontent.com/4691004/48907737-022cb680-ee71-11e8-8064-d3ee9efbf9c5.png">

In future releases, we plan to mark the current method as deprecated and add a new one(as a replacement).

**Comment by tadija** [comment]
Hi @andr-ggn, why is this issue closed when it's still present? Link from the previous comment is dead now, while API documentation states otherwise. What's the truth here, should we still pass `nil`?

**Comment by OliverPearmain** [comment]
I've opted for this...
```
        AppsFlyerLib.shared().continue(userActivity, restorationHandler: { input in
            let mappedInput = input?.compactMap { $0 as? UIUserActivityRestoring }
            return restorationHandler(mappedInput)
        })
```
