### ISSUE TITLE
Default property attribute 'assign' not appropriate for object

### ISSUE THREAD

**Issue by aeternas** [AppsFlyerSDK/AppsFlyerFramework#82]
Compiler warning arises when including the library (`@import AppsFlyerLib;`):

`AppsFlyerTracker.h:260:1: No 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed`
`AppsFlyerTracker.h:260:1: Default property attribute 'assign' not appropriate for object`

I don't know the exact cause, but it could be fixed by adding `strong` attribute to `appInviteOneLinkID` property.

**Comment by andr-ggn** [comment]
Hi, do you have a non arc project?

**Comment by aeternas** [comment]
Hi,
Nope, it is ARC project.
AppsFlyerNetwork is added via Cocoapods

**Comment by aeternas** [comment]
Hi team,
Are there any updates on the issue?

Kind regards,
Ivan

**Comment by andr-ggn** [comment]
We will add a correct attribute in the next release.
This is strange that you are the only one client, who complains of such kind of problem.
It would be great if you share with us a project where we can reproduce a problem.
Thx

**Comment by aeternas** [comment]
Great news, thanks!

The exact project is a bank app and I cannot share it. Kindly hope for your understanding. However, I will try to build a sample project and share it with you in case I reproduce this kind of bug.

Kind regards,
Ivan

**Comment by andr-ggn** [comment]
Will be available from 4.9.0. Soon
