### ISSUE TITLE
Crash on calling handleDidFinishLaunch, with version 4.9

### ISSUE THREAD

**Issue by hugebug4ever** [AppsFlyerSDK/AppsFlyerFramework#87]
it's triggered by launching app from URL Scheme ( for example: from safri). 
Here is the output and the calling stack (which was took while trying 4.8.11. 4.9 is the same):
--------------------------------------------------------------------------------------------------------------

AppsFlyer SDK version 4.8.11 started build (774)

[DEBUG] AppsFlyer: -[AppsFlyerTracker setIsDebug:] * * * AppsFlyer is set to debug mode. This should only be used in development enviornment!!!! * * *

[DEBUG] AppsFlyer: -[AppsFlyerTracker handleDidFinishLaunch:] Source application: com.apple.mobilesafari

[DEBUG] AppsFlyer: -[AppsFlyerTracker handleDidFinishLaunch:] Source application: com.apple.mobilesafari

    "0  CoreFoundation                 0x00000001bb33df20 CFRelease + 124",
    "1  CoreFoundation                 0x00000001bb39b7d4 0x00000001bb33c000 + 391124",
    "2  CoreFoundation                 0x00000001bb399b0c 0x00000001bb33c000 + 383756",
    "3  CoreFoundation                 0x00000001bb3999cc CFBundleGetBundleWithIdentifier + 240",
    "4  \U9583\U8000\U6696\U6696-\U958b\U767c                        0x0000000100fc6fbc -[AppsFlyerTracker handleDidFinishLaunch:] + 588",
    "5  CoreFoundation                 0x00000001bb3c6928 0x00000001bb33c000 + 567592",
    "6  CoreFoundation                 0x00000001bb3c68f4 0x00000001bb33c000 + 567540",
    "7  CoreFoundation                 0x00000001bb3c5de4 0x00000001bb33c000 + 564708",
    "8  CoreFoundation                 0x00000001bb3c5a90 0x00000001bb33c000 + 563856",
    "9  CoreFoundation                 0x00000001bb33dd70 0x00000001bb33c000 + 7536",
    "10 CoreFoundation                 0x00000001b<…>

**Comment by andr-ggn** [comment]
Hello, @hugebug4ever!

Can you reproduce a crash?

**Comment by hugebug4ever** [comment]
yes. it always crash.
but it's ok with 4.8.9, or earlier version

**Comment by hugebug4ever** [comment]
PS:
it's iOS 12+ only
it's ok with 11.x

**Comment by andr-ggn** [comment]
Can you share a code or demo application with a problem. This is interesting case.

**Comment by andr-ggn** [comment]
@hugebug4ever

**Comment by hugebug4ever** [comment]
It's a pity that we can not reproduce it with the demo project.
and our project is too large to be shared. 
The callstack seems pointed to some nulled pointer. 
If we can have some code snip around the stack, maybe we can guess what's wrong (conflicating) with AppFlyer.

**Comment by andr-ggn** [comment]
Can you call somewhere in your project:
```
CFBundleRef bundle = CFBundleGetBundleWithIdentifier((__bridge CFStringRef)@"com.apple.UIKit");
```

**Comment by andr-ggn** [comment]
Closed due to inactivity
