### ISSUE TITLE
Dependency "AppsFlyerFramework" has no shared framework schemes

### ISSUE THREAD

**Issue by basheer411** [AppsFlyerSDK/AppsFlyerFramework#88]
Downloading AppsFlyerFramework.framework binary at "4.10.0"
*** Skipped building AppsFlyerFramework due to the error:
Dependency "AppsFlyerFramework" has no shared framework schemes

**Comment by basheer411** [comment]
I could not able to update using Carthage for version 4.9.0 & 4.10.0

I have tried with both versions above, but the error is the same

**Comment by andr-ggn** [comment]
Hello, @basheer411! I will check and back to you.

**Comment by basheer411** [comment]
Hi,
Is there any update on this?

**Comment by andr-ggn** [comment]
@basheer411 

– I have created a New Project
– $: `touch Cartfile`
– Cartfile content: `binary "https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/AppsFlyerTracker.json" == 4.10.0`
– $:  `carthage update`
– Build Phases ->  New Run Script Phase -> paste `/usr/local/bin/carthage copy-frameworks`
– Input Files: `$(SRCROOT)/Carthage/Build/iOS/AppsFlyerTracker.framework`
– Output Files: `$(BUILT_PRODUCTS_DIR)/$(FRAMEWORKS_FOLDER_PATH)/AppsFlyerTracker.framework`
– Drag the .framework binaries from Carthage/Build/iOS into application’s Xcode project.
– `#import <AppsFlyerTracker/AppsFlyerTracker.h>`
– It works

Can you share Cartfile and check checkbox in Manage Schemes... -> Shared for AppsFlyerTracker

**Comment by basheer411** [comment]
my cart file is something like this 

github "AppsFlyerSDK/AppsFlyerFramework" ~> 4.10.0

**Comment by andr-ggn** [comment]
Have you checked steps above?

**Comment by basheer411** [comment]
yes, I have checked.

I am facing the following issue now.
**Dependency "AppsFlyerFramework" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/new**

**Comment by andr-ggn** [comment]
Can you try to replace `github "AppsFlyerSDK/AppsFlyerFramework" ~> 4.10.0` with `"https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/AppsFlyerTracker.json" == 4.10.0`
