### ISSUE TITLE
crash on +[AppsFlyerUtils isJailbroken]

### ISSUE THREAD

**Issue by tangbl93** [AppsFlyerSDK/AppsFlyerFramework#90]
![image](https://user-images.githubusercontent.com/13956214/59893529-beeaf400-940f-11e9-9e84-9687f6a3a619.png)

**Comment by tangbl93** [comment]
[banggood.shop_issue_crash_bc1e679f1386474db5844336ed45ee5a_DNE_1_v2.txt](https://github.com/AppsFlyerSDK/AppsFlyerFramework/files/3295068/banggood.shop_issue_crash_bc1e679f1386474db5844336ed45ee5a_DNE_1_v2.txt)

**Comment by af-fess** [comment]
@tangbl93 thank you, we will take a look.
Can you give more information about crash frequency?

**Comment by tangbl93** [comment]
crash frequency: 2 users crash 62 times
- SDK version : Pod AppsFlyerFramework (4.10.0)

**Comment by af-fess** [comment]
Looks like someone tries to spoof the iOS FileSystem. This is a  reason of the crash.

**Comment by af-fess** [comment]
This is was opened due to the frequency.  We are going to release the fix in  v4.10.2.

**Comment by andr-ggn** [comment]
fixed in v4.8.13

**Comment by titiphoque** [comment]
I'am stuck in 4.10.0 because binary Carthage is not up to date (https://raw.githubusercontent.com/AppsFlyerSDK/AppsFlyerFramework/master/AppsFlyerTracker.json)
When do you will release v4.10.3 for Carthage users ?
