### ISSUE TITLE
crash on +[AppsFlyerUtils isJailbrokenWithSkipAdvancedJailbreakValidation:]

### ISSUE THREAD

**Issue by tangbl93** [AppsFlyerSDK/AppsFlyerFramework#93]
Maybe the same reason as this #90 

# Fabric

crash frequency: 2 users crash 56 times
SDK version : Pod AppsFlyerFramework (4.10.3)

![image](https://user-images.githubusercontent.com/13956214/62432952-ecdc8b80-b764-11e9-9001-4c21161006d2.png)

[issue_crash_0fb26a334aa24674920a3d9d8548ccf7_DNE_2_v2.txt](https://github.com/AppsFlyerSDK/AppsFlyerFramework/files/3465617/issue_crash_0fb26a334aa24674920a3d9d8548ccf7_DNE_2_v2.txt)

**Comment by andr-ggn** [comment]
This is bad jailbroken devices.
If you dare about them - 
type `[[AppsFlyerTracker sharedTracker] setValue:@YES forKey:@"skipAdvancedJailbreakValidation"];` before AppsFlyer setup

**Comment by andr-ggn** [comment]
And your *two* will stop to crash

**Comment by tangbl93** [comment]
nice
