### ISSUE TITLE
Support for Swift package manager

### ISSUE THREAD

**Issue by allanscofield** [AppsFlyerSDK/AppsFlyerFramework#94]
Please, add support for Swift Package Manager.

**Comment by andr-ggn** [comment]
Coming soon 👍

**Comment by Banck** [comment]
any news?

**Comment by intelmehra** [comment]
Any News?

**Comment by andr-ggn** [comment]
SwiftPM cannot distribute packages containing binary frameworks.
https://github.com/apple/swift-evolution/blob/master/proposals/0272-swiftpm-binary-dependencies.md
As far, as I know it is still in a progress..

**Comment by xMythicx** [comment]
+ 1, Would love to see this feature.

**Comment by bettola** [comment]
Upvoting. We need this please.

**Comment by ss42** [comment]
+1

**Comment by bpapa** [comment]
Please add support for this. I haven't updated our AppsFlyer in quite awhile and now that I'm using SPM with Amplitude, this is the only way I want to manage dependencies going forward.

**Comment by andr-ggn** [comment]
https://forums.swift.org/t/spm-support-for-binaries-distribution/25549/45

**Comment by momoohidayat** [comment]
https://github.com/apple/swift-evolution/blob/master/proposals/0272-swiftpm-binary-dependencies.md

implemented on swift 5.3

**Comment by Exey** [comment]
Upvoting

**Comment by mccarron** [comment]
Upvoting as well. Plan on dropping Cocoapods as soon as we can.

**Comment by OlexandrStepanov** [comment]
➕

**Comment by IvanShah** [comment]
upvote, it's important!

**Comment by alak** [comment]
👍

**Comment by andreyoshev** [comment]
up

**Comment by pf-brunoreginato** [comment]
Up!

**Comment by EmperiorEric** [comment]
We need this.

**Comment by thefaj** [comment]
Could someone from AppsFlyer respond here? /cc @af-fess

**Comment by alak** [comment]
ping @af-fess can you help us ?

**Comment by thefaj** [comment]
> SwiftPM cannot distribute packages containing binary frameworks.
> https://github.com/apple/swift-evolution/blob/master/proposals/0272-swiftpm-binary-dependencies.md
> As far, as I know it is still in a progress..

This is incorrect. Swift Package Manager can definitely distribute binaries. Here is the documentation: https://developer.apple.com/documentation/swift_packages

Can *somebody* from AppsFlyer respond back?? @af-fess anybody??

**Comment by andr-ggn** [comment]
https://github.com/AppsFlyerSDK/AppsFlyerFramework/pull/138

**Comment by thefaj** [comment]
Why was this closed without comment?

**Comment by andr-ggn** [comment]
@thefaj 
You have been writing apps since 2008 and you need comments in this case?

**Comment by thefaj** [comment]
@andr-ggn Please act professionally here. This is a serious blocking issue. EVERYONE on this thread would appreciate a formal response from the company responsible for this codebase.

**Comment by alak** [comment]
@thefaj they merged a PR to support SPM yesterday :) https://github.com/AppsFlyerSDK/AppsFlyerFramework/pull/138

**Comment by af-fess** [comment]
Hi @thefaj 
I very sorry your experience is less than perfect. 
Last week we added the support for [Swift Package Manager](https://github.com/AppsFlyerSDK/AppsFlyerFramework/blob/master/Package.swift)

**Comment by ashender** [comment]
https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/157
