### ISSUE TITLE
minTimeBetweenSessions affecting deep link callbacks

### ISSUE THREAD

**Issue by teffi** [AppsFlyerSDK/AppsFlyerFramework#97]
Is there any plan to fix the side effect of high value `minTimeBetweenSessions` on deep linking? Or is there any suggested workarounds for managing time in between session w/o conflicting with the deep link workflow of the framework? 

It's really not helpful in making sense of data when we are forced to keep this on low value when the standard session timeout for apps is usually 60-30 seconds.

`AppsFlyerTracker.shared().minTimeBetweenSessions = <your_custom_time_in_seconds>`

**Comment by BenjaminAF** [comment]
Hi teffi,

Like you suggested, the current design has this impact on deep linking of minTimeBetweenSessions. We are aware of this, and will look to improve it in one of the future versions.

**Comment by andr-ggn** [comment]
We added to our plans.
