### ISSUE TITLE
[suggestion] Read data receive by constants and check status value using enum

### ISSUE THREAD

**Issue by GeraldoBastos** [AppsFlyerSDK/AppsFlyerFramework#98]
I'm checking the sample page to read data in `onConversionDataReceive` for `iOS` in this URL: https://support.appsflyer.com/hc/en-us/articles/207032096-Deferred-deep-linking-getting-the-conversion-data#sdk-implementation.

I think that the good approach to read important values in Swift dictionary with the specific keys is using the constants, for example when I need to access the _status_ (organic or non-organic) value and check if the _first launch_ with respective keys: `"af_status"` and `"is_first_launch"` in installData param I don't use any variable/constant to find this data.

We can implement something like this to the data keys and check status value:

<img width="412" alt="Captura de Tela 2019-10-11 às 10 22 40" src="https://user-images.githubusercontent.com/992210/66656328-2376cc80-ec14-11e9-87ef-ada3ec3b934a.png">

And if the Appsflyer needs to change the keys, it'll not a problem for us that use the sdk because we use the constant to read the data receive.

**Comment by af-fess** [comment]
This issue has been inactive for a while, and will now be closed due to inactivity. If you still believe this is a valid issue, please feel free to reopen it or create a new issue with updated information.
